Repository ynput/ayon-frontend, pull requests merged in 2024-12, with the labels that each got.

#942 Settings: fix disappearing default values
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/SettingsEditor/Widgets/CheckboxWidget.tsx
  src/containers/SettingsEditor/Widgets/SelectWidget.tsx
  src/containers/SettingsEditor/Widgets/TextWidget.tsx
  src/containers/SettingsEditor/helpers.ts
Labels: type: bug

#939 Permissions: Studio settings separated from project specific ones
  src/pages/ProjectManagerPage/ProjectManagerPage.jsx
  src/pages/ProjectManagerPage/ProjectPermissions.jsx
  src/pages/SettingsPage/AccessGroups/AccessGroupList.jsx
  src/pages/SettingsPage/AccessGroups/index.jsx
  src/pages/SettingsPage/AccessGroups/index.tsx
  src/pages/SettingsPage/SettingsPage.jsx
Labels: type: enhancement

#944 Project Settings: limited access users UI/UX changes
  src/api/rest/accessGroups.ts
  src/api/rest/users.ts
  src/app.jsx
  src/components/Menu/Menus/AppMenu.jsx
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/projectList.jsx
  src/context/shortcutsContext.jsx
  src/hooks/useUserProjectPermissions.ts
  src/pages/ProjectManagerPage/ProjectAnatomy.jsx
  src/pages/ProjectManagerPage/ProjectManagerPage.jsx
  src/pages/ProjectManagerPage/ProjectRoots.jsx
  src/pages/ProjectManagerPage/Users/AccessGroupsCell.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccess.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAssignDialog.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessProjectList.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessUserList.tsx
  src/pages/ProjectManagerPage/Users/UserCell.tsx
  src/pages/ProjectManagerPage/Users/hooks.ts
  src/pages/ProjectManagerPage/Users/mappers.ts
  src/pages/ProjectManagerPage/mappers.ts
  src/services/accessGroups/getAccessGroups.ts
  src/services/accessGroups/updateAccessGroups.ts
  src/services/project/getProject.ts
  tests/fixtures/projectUserAccessGroupsPage.ts
Labels: type: bug

#948 Permissions: UI/UX fixes & typo bugfix
  src/components/EmptyPlaceholder/EmptyPlaceholderFlex.styled.ts
  src/pages/ProjectManagerPage/ProjectManagerPage.jsx
  src/pages/ProjectManagerPage/ProjectPermissions.jsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccess.styled.ts
  src/pages/ProjectManagerPage/Users/ProjectUserAccess.tsx
  src/pages/ProjectManagerPage/mappers.ts
  src/pages/SettingsPage/AccessGroups/index.tsx
Labels: type: bug

#949 Market: Show releases on Market page
  .__mf__temp/ShellApp/localSharedImportMap.js
  .gitignore
  src/api/rest/releases.ts
  src/components/AddonIcon/AddonIcon.styled.ts
  src/components/AddonIcon/AddonIcon.tsx
  src/components/CloudButton/CloudButton.tsx
  src/components/CloudButton/index.ts
  src/components/EmptyPlaceholder/EmptyPlaceholder.tsx
  src/components/MarketAddonCard/MarketAddonCard.jsx
  src/components/MarketAddonCard/MarketAddonCard.styled.ts
  src/components/MarketAddonCard/MarketAddonCard.tsx
  src/components/MarketAddonCard/MarketAddonCardGroup.tsx
  src/components/MarketAddonCard/index.ts
  src/components/Menu/Menus/AppMenu.jsx
  src/components/YnputCloud/YnputCloud.styled.js
  src/components/YnputCloud/YnputConnector.jsx
  src/containers/ReleaseInstallerDialog/ReleaseInstaller.tsx
  src/containers/ReleaseInstallerDialog/ReleaseInstallerDialog.tsx
  src/containers/ReleaseInstallerDialog/ReleaseInstallerPrompt/ReleaseInstallerPrompt.tsx
  src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerProgress.tsx
  src/containers/ReleaseInstallerDialog/helpers.ts
  src/containers/ReleaseInstallerDialog/hooks/useReleaseForm.ts
  src/features/releaseInstaller.ts
  src/pages/MarketPage/AddonFilters.jsx
  src/pages/MarketPage/MarketAddonsList.jsx
  src/pages/MarketPage/MarketAddonsList.tsx
  src/pages/MarketPage/MarketDetails/AddonDetails.tsx
  src/pages/MarketPage/MarketDetails/MarketDetails.styled.ts
  src/pages/MarketPage/MarketDetails/MetaPanelRow.tsx
  src/pages/MarketPage/MarketDetails/ReleaseDetails.tsx
  src/pages/MarketPage/MarketDetails/useDownload.js
  src/pages/MarketPage/MarketDetails/useUninstall.js
  src/pages/MarketPage/MarketFilters.tsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/helpers/filterItems.ts
  src/pages/MarketPage/helpers/index.ts
  src/pages/MarketPage/helpers/transformReleasesToTable.ts
  src/pages/MarketPage/hooks/index.ts
  src/pages/MarketPage/hooks/useExpandedGroups.ts
  src/pages/SettingsPage/AddonsManager/AddonsManager.jsx
  src/pages/SettingsPage/Bundles/BundlesAddonList.jsx
Labels: type: feature

#954 fix(URI): Removed wrong conditional that blocked navigation on URI init
  src/containers/Breadcrumbs/Breadcrumbs.jsx
  src/containers/SettingsEditor/SettingsEditor.jsx
  src/context/uriContext.jsx
Labels: type: bug

#961 License control
  gen/openapi-config.ts
  src/api/rest/auth.ts
  src/components/DetailHeader.jsx
  src/components/User/UserDetailsHeader.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/SettingsPage/UsersSettings/UserLicenseForm.tsx
  src/pages/SettingsPage/UsersSettings/UserList.jsx
  src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
  src/services/auth/getAuth.js
  src/services/ayon.ts
  src/services/user/getUsers.ts
  src/services/user/updateUser.ts
Labels: type: maintenance

#957 A: Remote setup
  gen/openapi-config.ts
  package.json
  src/api/rest/addons.ts
  src/app.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/helpers.jsx
  src/components/CommentInput/hooks/useAnnotationsSync.ts
  src/components/CommentInput/hooks/useAnnotationsUpload.ts
  src/components/FileUploadCard/FileUploadCard.jsx
  src/components/FileUploadCard/FileUploadCard.styled.js
  src/components/ReviewVersionDropdown/ReviewVersionDropdown.tsx
  src/components/ReviewablesSelector/ReviewablesSelector.styled.ts
  src/components/ReviewablesSelector/ReviewablesSelector.tsx
  src/containers/FilesGrid/FilesGrid.jsx
  src/containers/ReviewablesList/ReviewablesUpload.tsx
  src/containers/VideoPlayer/Trackbar.jsx
  src/containers/VideoPlayer/VideoPlayer.jsx
  src/containers/VideoPlayer/VideoPlayerControls.jsx
  src/containers/VideoPlayer/hooks/useGoToFrame.ts
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/Viewer.tsx
  src/containers/Viewer/ViewerComponent.tsx
  src/containers/Viewer/ViewerDetailsPanel.tsx
  src/containers/Viewer/ViewerDialog.tsx
  src/containers/Viewer/ViewerHistory.tsx
  src/containers/Viewer/ViewerImage.tsx
  src/containers/Viewer/ViewerPlayer.tsx
  src/containers/Viewer/hooks/useViewerAnnotations.ts
  src/containers/Viewer/index.ts
  src/context/slicerContext.tsx
  src/context/viewerContext.tsx
  src/features/context.js
  src/features/middleware/getInitialStateQueryParam.ts
  src/features/viewer.js
  src/features/viewer.ts
  src/index.tsx
  src/remote/registerAddonRemotes.ts
  src/remote/useLoadModule.ts
  src/remote/useRegisterRemotes.ts
  src/services/addons/getAddons.ts
  src/services/review/types.ts
  vite.config.ts
Labels: type: enhancement

#964 Task progress: spacebar to open selected folder
  src/containers/TasksProgress/TasksProgress.tsx
  src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
  src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
  src/containers/Viewer/Viewer.tsx
Labels: type: bug
