Repository ynput/ayon-frontend, pull requests merged in 2024-10, with the labels that each got.

#822 Attributes: New enum editor with support for colours and icons
  src/components/EnumEditor/DraggableEnumEditorItem.tsx
  src/components/EnumEditor/EnumEditor.styled.ts
  src/components/EnumEditor/EnumEditor.tsx
  src/components/EnumEditor/hooks/useDraggable.ts
  src/containers/attributes/attributeEditor.jsx
  src/containers/attributes/enumEditor.jsx
  src/helpers/string.ts
Labels: type: feature

#837 Editor: Fixed crash condition on assignee update
  src/pages/EditorPage/EditorPanel/EditorPanel.jsx
  src/pages/EditorPage/EditorPanel/helper/callbacks.js
  src/pages/EditorPage/EditorPanel/helper/entityHelpers.ts
Labels: type: bug

#843 Reactions: Reactions stay hidden while editing comment
  src/components/Feed/ActivityComment/ActivityComment.tsx
Labels: type: bug

#842 Attributes: Using EnumDropdown for options icon/color support
  gen/graphql.schema.json
  gen/openapi-config.ts
  package.json
  src/api/graphql.ts
  src/api/rest/attributes.ts
  src/components/EnumEditor/DraggableEnumEditorItem.tsx
  src/containers/TasksProgress/TasksProgress.tsx
  src/containers/TasksProgress/components/TaskTypeCell/TaskTypeCell.tsx
  src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
  src/containers/TasksProgress/helpers/index.ts
  src/containers/TasksProgress/helpers/operations.ts
  src/containers/attributeTable.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/EditorPage/EditorPanel/EnumRow.tsx
  src/pages/EditorPage/utils.jsx
  src/pages/SettingsPage/Attributes.jsx
  src/pages/TasksProgressPage/TasksProgressPage.tsx
  src/pages/TasksProgressPage/helpers/getPriorityOptions.ts
  src/pages/TasksProgressPage/helpers/index.ts
  src/services/attributes/getAttributes.js
  src/services/attributes/getAttributes.ts
  src/services/attributes/updateAttributes.js
  src/services/attributes/updateAttributes.ts
  src/services/tasksProgress/gql/ProgressTaskFragment.graphql
Labels: type: enhancement

#840 Statuses: Statuses filtered by project scope configuration
  src/app.jsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/Viewer/ViewerDetailsPanel.jsx
  src/hooks/useScopedStatuses.ts
  src/pages/BrowserPage/BrowserDetailsPanel.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/EditorPage/EditorPanel/EditorPanel.jsx
  src/pages/InboxPage/InboxDetailsPanel.jsx
  src/pages/TasksProgressPage/TaskProgressDetailsPanel.jsx
  src/pages/TasksProgressPage/TasksProgressPage.tsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
  src/services/userDashboard/getUserDashboard.ts
Labels: type: feature

#852 Editor: Date picker z index
  src/styles/index.scss
Labels: type: bug

#853 Addons: Fixed missing context issues, style improvements
  src/hooks/useAddonContextResend.ts
  src/pages/ProjectAddon.jsx
  src/pages/SettingsPage/SettingsAddon.jsx
Labels: type: bug

#844 Previewer: Closing preview modal when clicking outside content/nav arrows.
  src/containers/FileUploadPreview/FileUploadPreview.jsx
  src/containers/Viewer/ViewerDialog.tsx
  src/features/context.js
Labels: type: bug

#859 Entity Panel: Entity details panel picture in picture modal
  gen/graphql.schema.json
  src/api/graphql.ts
  src/app.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/Feed/ActivityComment/ActivityComment.tsx
  src/components/Feed/ActivityReference/ActivityReference.jsx
  src/components/Thumbnail/Thumbnail.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.styled.ts
  src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.tsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/DetailsPanel/FeedFilters/FeedFilters.jsx
  src/containers/DetailsPanel/helpers/getThumbnails.ts
  src/containers/Feed/Feed.jsx
  src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
  src/context/pip/PiPProvider.tsx
  src/context/pip/PiPWindow.tsx
  src/context/pip/PiPWrapper.tsx
  src/context/pip/globals.d.ts
  src/context/shortcutsContext.jsx
  src/features/details.js
  src/pages/EditorPage/StackedThumbnails.tsx
  src/pages/InboxPage/Inbox/Inbox.jsx
  src/services/user/getUsers.ts
  src/services/user/gql/GetAllAssignees.graphql
Labels: type: feature

#863 Addons: Removed overlay blocking addon iframe
  src/pages/ProjectAddon.jsx
  src/pages/SettingsPage/SettingsAddon.jsx
Labels: type: bug

#868 Bundles: Avoiding potential errors caused by server restart
  src/services/installers/getInstallers.ts
  src/services/project/getProject.ts
Labels: type: bug

#874 Viewer: Fixed error on add reviewable button click
  src/containers/Viewer/Viewer.tsx
Labels: type: bug

#871 Specs: Fixing faulty specs
  playwright.config.js
  src/pages/SettingsPage/UsersSettings/DeleteUserDialog.tsx
  tests/auth.setup.js
  tests/fixtures/authenticationPage.ts
  tests/fixtures/browserPage.ts
  tests/fixtures/installRelease.ts
  tests/fixtures/taskPage.ts
  tests/fixtures/userPage.ts
Labels: type: maintenance

#865 854 support drag and drop reordering for list fields
  package.json
  src/containers/SettingsEditor/FormTemplates/ArrayFieldItemTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/DraggableItem.tsx
  src/containers/SettingsEditor/FormTemplates/FieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
  src/containers/SettingsEditor/SettingsEditor.jsx
  src/containers/SettingsEditor/SettingsEditor.sass
  src/containers/SettingsEditor/Widgets/CheckboxWidget.tsx
  src/containers/SettingsEditor/Widgets/DateTimeWidget.tsx
  src/containers/SettingsEditor/Widgets/SelectWidget.tsx
  src/containers/SettingsEditor/Widgets/TextWidget.tsx
  src/containers/SettingsEditor/fields.jsx
  src/containers/SettingsEditor/helpers.ts
  src/containers/SettingsEditor/widgets.jsx
Labels: type: feature

#887 PiP: users query all users can access
  src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.tsx
Labels: type: bug

#886 Task Progress: Table style improvements
  src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts
  src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
  src/containers/TasksProgress/components/ParentBody/ParentBody.tsx
  src/containers/TasksProgress/components/TasksProgressTable/TaskProgressTable.scss
  src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
  src/styles/index.scss
Labels: type: enhancement, sponsored

#891 Events: Removed row icon ellipsis in events table
  src/pages/EventsPage/EventList.jsx
Labels: type: bug

#890 Addons: Fixed Cancel/Close button message on addon upload
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
Labels: type: bug

#889 Settings: Fixed scroll behavior in raw edit mode
  src/containers/RawSettingsDialog/RawSettingsDialog.jsx
Labels: type: bug

#880 Settings: Wide settings lists are now scrollable
  src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx
  src/containers/SettingsEditor/SettingsPanel.jsx
Labels: type: bug

#893 Watchers: Invalidate versions watchers when changing tasks watchers
  src/containers/Watchers/Watchers.tsx
  src/pages/TasksProgressPage/TasksProgressPage.tsx
  src/services/watchers.ts
Labels: type: bug

#895 fix(Settings): Min container width set to 100% to avoid narrow content issues
  src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx
Labels: type: bug

#913 Bundles: copy settings from... broken
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.tsx
Labels: type: bug

#915 Task Progress: Folder selection
  package.json
  src/api/graphql.ts
  src/components/SearchFilter/SearchFilter.styled.ts
  src/components/Thumbnail/Thumbnail.tsx
  src/containers/TasksProgress/TasksProgress.tsx
  src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts
  src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
  src/containers/TasksProgress/components/ParentBody/ParentBody.styled.ts
  src/containers/TasksProgress/components/ParentBody/ParentBody.tsx
  src/containers/TasksProgress/components/TasksProgressTable/TasksProgressTable.tsx
  src/containers/TasksProgress/helpers/formatTaskProgressForTable.ts
  src/containers/TasksProgress/helpers/taskStatusSortFunction.ts
  src/features/progress.ts
  src/features/store.ts
  src/pages/TasksProgressPage/TaskProgressDetailsPanel.tsx
  src/pages/TasksProgressPage/TasksProgressPage.tsx
  src/services/tasksProgress/gql/ProgressTaskFragment.graphql
Labels: type: enhancement, sponsored

#914 Dashboard: Show addons that are scoped to dashboard
  src/app.jsx
  src/pages/ProjectDashboard/DashboardAddon.jsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
  src/services/addons/getAddons.ts
Labels: type: enhancement
