Repository ynput/ayon-frontend, pull requests merged in 2024-04, with the labels that each got.

#305 fix: throttle websocket overload
  src/components/RefreshToast.jsx
  src/context/websocketContext.jsx
Labels: bug

#329 Active/Inactive state visual differentiation for tasks
  src/containers/taskList.jsx
  src/helpers/parseTasksList.js
  src/pages/EditorPage/EditorPanel.jsx
  src/services/getTasks.js
Labels: enhancement

#312 Dashboard renamed to Home
  src/containers/header/AppHeader.jsx
  src/containers/header/HeaderButton.jsx
Labels: enhancement

#337 fix: added tabindex to skip clearfield when pressing tab
  src/pages/EditorPage/EditorPanel.jsx
Labels: bug

#346 fix: db click only expands folders
  src/pages/EditorPage/EditorPage.jsx
Labels: bug

#308 Save context when refreshing page
  src/containers/hierarchy.jsx
  src/containers/taskList.jsx
  src/features/context.js
  src/features/middleware/getInitialStateLocalStorage.js
  src/features/middleware/localStorageMiddleware.js
  src/index.jsx
  src/pages/BrowserPage/Products.jsx
  src/pages/BrowserPage/ProductsList.jsx
  src/pages/BrowserPage/VersionList.jsx
  src/pages/ProjectPage.jsx
  src/pages/WorkfilesPage/WorkfileDetail.jsx
  src/pages/WorkfilesPage/WorkfileList.jsx
  src/pages/WorkfilesPage/WorkfilesPage.jsx
  src/services/product/getProduct.js
Labels: enhancement

#350 fix: check if projectName is not falsy (undefined, null) for request
  src/components/ThumbnailUploader/ThumbnailUploader.jsx
  src/containers/ThumbnailSimple.jsx
  src/containers/thumbnail.jsx
  src/pages/BrowserPage/ProductsGrid.jsx
  src/pages/ProjectDashboard/panels/ProjectLatestRow.jsx
Labels: bug

#351 fix: remove other roles if user is admin/manager
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
Labels: bug

#364 Settings copy fix
  src/containers/SettingsEditor/fields.jsx
  src/services/addonSettings.js
Labels: HIGH, bug

#365 Representations selection and context menu
  src/components/Details/EntityDetailsPanel.jsx
  src/features/context.js
  src/pages/BrowserPage/Detail.jsx
  src/pages/BrowserPage/RepresentationList.jsx
  src/services/entity/entityQueries.js
  src/services/entity/getEntity.js
Labels: enhancement

#368 fix: Added new 'Status' column in EditorPage
  src/pages/EditorPage/EditorPage.jsx
  src/pages/EditorPage/utils.jsx
  src/pages/EditorPage/utils.styled.js
Labels: enhancement

#374 fix: Added submit on ctrl/meta + enter to access group dialog
  src/pages/SettingsPage/AccessGroups/NewAccessGroup.jsx
Labels: bug
