Repository ynput/ayon-frontend, pull requests merged in 2024-05, with the labels that each got.

#381 fix: icon type and text fix
  src/pages/SettingsPage/Bundles/BundlesAddonList.jsx
Labels: bug

#383 fix: version status not updating in browser UI
  src/containers/entityDetail.jsx
  src/pages/BrowserPage/Detail.jsx
  src/pages/BrowserPage/Products.jsx
  src/pages/BrowserPage/VersionList.jsx
  src/services/ayon.js
  src/services/entity/entityQueries.js
  src/services/product/getProduct.js
Labels: HIGH, bug

#357 Replace primereact dialogues with ARC
  src/components/DetailHeader.jsx
  src/components/ShareDialog.jsx
  src/containers/CopySettings/CopySettingsDialog.jsx
  src/containers/RawSettingsDialog/RawSettingsDialog.jsx
  src/containers/attributes/attributeEditor.jsx
  src/containers/entityDetail.jsx
  src/context/pasteContext.jsx
  src/pages/EditorPage/NewEntity.jsx
  src/pages/EditorPage/NewSequence.jsx
  src/pages/MarketPage/ConnectDialog/ConnectDialog.jsx
  src/pages/ProjectAddon.jsx
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
  src/pages/ProjectPage.jsx
  src/pages/ServicesPage/NewServiceDialog.jsx
  src/pages/SettingsPage/AccessGroups/NewAccessGroup.jsx
  src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
  src/pages/SettingsPage/Attributes.jsx
  src/pages/SettingsPage/Bundles/BundleDeps.jsx
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/pages/SettingsPage/UsersSettings/RenameUserDialog.jsx
  src/pages/SettingsPage/UsersSettings/SetPasswordDialog.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/pages/TeamsPage/TeamsPage.jsx
Labels: enhancement

#386 Fix: move access groups to under access level
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
Labels: enhancement

#391 Activity feed: dev fixes
  package.json
  src/components/Actions/Actions.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInput.styled.js
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
  src/components/Feed/ActivityHeader/ActivityHeader.styled.js
  src/components/Feed/ActivityItem.jsx
  src/containers/Feed/Feed.jsx
  src/containers/Feed/Feed.styled.js
  src/containers/Feed/hooks/useCommentMutations.js
  src/containers/Feed/hooks/useSaveScrollPos.js
  src/containers/Feed/hooks/useTransformActivities.js
  src/containers/FileUploadPreview/FileUploadPreview.jsx
  src/containers/ThumbnailSimple.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardDetails/UserDashboardDetails.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardSlideOut/UserDashboardSlideOut.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
  src/pages/UserDashboardPage/util/usePrefetchTask.js
  src/services/userDashboard/getUserDashboard.js
  src/services/userDashboard/userDashboardQueries.js
Labels: bug

#395 fix(bundles): Cannot assign to read only property 'isDev
  src/pages/SettingsPage/Bundles/NewBundle.jsx
Labels: bug

#400 fix(comment): \\ replaced with \\\ so that it renders as \\
  src/components/CommentInput/helpers.jsx
Labels: bug

#401 fix(comment): checklists cursor misaligned
  src/components/CommentInput/CommentInput.styled.js
Labels: bug

#402 Editor: ensure attrib fields with inherit=false are not inherited
  src/pages/EditorPage/EditorPage.jsx
Labels: bug

#407 Dialog blur fix
  package.json
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
Labels: bug

#394 fix: replaced user data source to server for showing developer mode
  src/containers/header/AppHeader.jsx
  src/features/user.js
  src/pages/AccountPage/ProfilePage.jsx
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
Labels: bug

#404 fix(bundles): ensure only addons that are still installed copy across
  src/pages/SettingsPage/Bundles/Bundles.jsx
Labels: bug

#403 Pinning settings using changelist
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/AddonSettings/VariantSelector.jsx
  src/containers/BundleDropdown.jsx
  src/containers/CopySettings/CopySettingsDialog.jsx
  src/containers/CopySettings/CopySettingsNode.jsx
  src/containers/ProjectDropdown.jsx
  src/containers/SettingsEditor/fields.jsx
  src/containers/SettingsEditor/widgets.jsx
Labels: enhancement

#411 Activity Feed: general bug fixes
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInput.styled.js
  src/components/CommentInput/InputMarkdownConvert.jsx
  src/components/CommentInput/helpers.jsx
  src/components/CommentInput/quillToMarkdown.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
  src/pages/UserDashboardPage/util/usePrefetchTask.js
Labels: maintenance

#425 Bootstrap: fix first bundle creation after bootstrapping
  src/pages/OnBoarding/util/OnBoardingContext.jsx
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
  src/services/dependencyPackages.js
  src/services/onBoarding/onBoarding.js
Labels: bug

#429 Comment: fullName undefined on new comment
  src/containers/Feed/hooks/useCommentMutations.js
Labels: bug

#427 Browser: Filter products/versions list by taskType
  package.json
  src/components/CategorySelect/CategorySelect.jsx
  src/components/CategorySelect/CategorySelect.styled.js
  src/containers/taskList.jsx
  src/features/context.js
  src/hooks/useSearchFilter.js
  src/pages/BrowserPage/BrowserPage.jsx
  src/pages/BrowserPage/Products/NoProducts.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/BrowserPage/Products/Products.styled.js
  src/pages/BrowserPage/Products/ProductsGrid.jsx
  src/pages/BrowserPage/Products/ProductsList.jsx
  src/pages/BrowserPage/Products/VersionList.jsx
  src/pages/BrowserPage/Products/ViewModeToggle.jsx
  src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.jsx
  src/services/product/getProduct.js
Labels: feature

#433 fix(upload): fix displaying error messages for addon upload
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
Labels: bug

#431 Market: replaced 'install' with 'download'
  src/components/MarketAddonCard/MarketAddonCard.jsx
  src/components/MarketAddonCard/MarketAddonCard.styled.js
  src/pages/MarketPage/AddonDetails/AddonDetails.jsx
  src/pages/MarketPage/AddonFilters.jsx
  src/pages/MarketPage/MarketAddonsList.jsx
Labels: bug

#440 Fixed pasting array fields to the anatomy editor
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/AnatomyEditor.jsx
Labels: bug

#438 Bundles: fix context selection change for archiving and deleting
  src/pages/SettingsPage/Bundles/BundleForm.jsx
  src/pages/SettingsPage/Bundles/BundleList.jsx
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/pages/SettingsPage/Bundles/InstallerSelector.jsx
Labels: bug

#450 Preview: Details panel header compact mode
  src/components/Actions/Actions.jsx
  src/components/status/statusField.jsx
  src/components/status/statusSelect.jsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
  src/containers/DetailsPanel/FeedFilters/FeedFilters.jsx
Labels: enhancement

#447 Editor: Editor dragging a value does not trigger thumbnail upload
  src/components/ThumbnailUploader/ThumbnailUploader.jsx
  src/components/ThumbnailUploader/ThumbnailUploader.styled.js
  src/containers/thumbnail.jsx
  src/features/editor.js
  src/pages/EditorPage/EditorPage.jsx
Labels: bug

#435 Onboarding: Show addon version when selecting addons
  src/components/AddonCard/AddonCard.jsx
  src/components/AddonCard/AddonCard.styled.jsx
  src/pages/OnBoarding/Step/AddonSelectStep.jsx
  src/pages/OnBoarding/util/OnBoardingContext.jsx
  src/pages/OnBoarding/util/OnBoardingStep.styled.js
Labels: enhancement

#451 Browser: Columns select dropdown
  src/components/ColumnsSelect/ColumnsSelect.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/BrowserPage/Products/Products.styled.js
Labels: bug

#458 Comment: attachments fixes
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/modules/index.js
  src/components/FileUploadCard/FileUploadCard.jsx
  src/components/FileUploadCard/FileUploadCard.styled.js
  src/containers/FileUploadPreview/FileUploadPreview.jsx
Labels: bug

#464 Type Editor: Dropdown order of folders and tasks now respect settings order
  src/pages/EditorPage/NewEntity.jsx
  src/pages/EditorPage/NewSequence.jsx
  src/pages/EditorPage/TypeEditor.jsx
Labels: bug

#469 URI: Fix wrong URI on different pages
  src/app.jsx
  src/containers/Breadcrumbs/Breadcrumbs.jsx
  src/context/uriContext.jsx
  src/pages/ProjectDashboard/panels/ProjectLatest.jsx
  src/pages/UserDashboardPage/util/useGetTaskContextMenu.js
Labels: bug

#467 File Preview: Support for text files and PDFs
  src/components/FileUploadCard/FileUploadCard.jsx
  src/components/FileUploadCard/FileUploadCard.styled.js
  src/containers/FileUploadPreview/FileUploadPreview.jsx
  src/containers/FileUploadPreview/FileUploadPreview.styled.js
  src/containers/FileUploadPreview/mimes/ImageMime.jsx
  src/containers/FileUploadPreview/mimes/TextMime.jsx
  src/features/context.js
Labels: feature

#472 Shortcuts: show shortcuts more in context menus
  src/components/ContextMenu/ContextMenu.scss
  src/components/ContextMenu/ContextMenuItem.jsx
  src/components/Menu/MenuComponents/Menu.styled.js
  src/components/Menu/MenuComponents/MenuItem.jsx
  src/components/ShortcutWidget/ShortcutWidget.jsx
  src/hooks/Tooltip/Tooltip.styled.js
  src/hooks/Tooltip/useTooltip.jsx
  src/hooks/useCreateContext.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/SettingsPage/Bundles/BundleList.jsx
  src/styles/index.scss
Labels: enhancement

#460 Inbox MVP
  package.json
  src/app.jsx
  src/components/CommentInput/CommentInput.styled.js
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
  src/components/Feed/ActivityDate.jsx
  src/components/Feed/ActivityHeader/ActivityHeader.jsx
  src/components/Feed/ActivityReference/ActivityReference.jsx
  src/components/Menu/MenuComponents/Menu.styled.js
  src/components/NoEntityFound.jsx
  src/components/Tooltips/UserTooltip/UserTooltip.styled.js
  src/containers/Breadcrumbs/Breadcrumbs.jsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/Feed/Feed.jsx
  src/containers/Feed/feedHelpers.jsx
  src/containers/Feed/hooks/useSaveScrollPos.js
  src/containers/Feed/hooks/useScrollToHighlighted.js
  src/containers/header/AppHeader.jsx
  src/containers/header/AppNavLinks.jsx
  src/containers/header/HeaderButton.jsx
  src/context/shortcutsContext.jsx
  src/features/details.js
  src/features/middleware/getInitialStateQueryParam.js
  src/helpers/getEntityTypeIcon.js
  src/pages/EditorPage/fields/NameField.jsx
  src/pages/InboxPage/Inbox/Inbox.jsx
  src/pages/InboxPage/Inbox/Inbox.styled.js
  src/pages/InboxPage/InboxDetailsPanel.jsx
  src/pages/InboxPage/InboxMessage/InboxMessage.jsx
  src/pages/InboxPage/InboxMessage/InboxMessage.styled.js
  src/pages/InboxPage/InboxMessage/InboxMessageStatus/InboxMessageStatus.jsx
  src/pages/InboxPage/InboxMessage/InboxMessageStatus/InboxMessageStatus.styled.js
  src/pages/InboxPage/InboxPage.jsx
  src/pages/InboxPage/hooks/useGroupMessages.js
  src/pages/InboxPage/hooks/useInboxRefresh.js
  src/pages/InboxPage/hooks/useKeydown.js
  src/pages/InboxPage/hooks/useUpdateInboxMessage.js
  src/pages/InboxPage/index.jsx
  src/pages/ProjectDashboard/panels/ProjectStats.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
  src/pages/UserDashboardPage/util/index.js
  src/pages/UserDashboardPage/util/usePrefetchEntity.js
  src/services/activities/activitiesHelpers.js
  src/services/activities/activityQueries.js
  src/services/activities/getActivities.js
  src/services/activities/updateActivities.js
  src/services/ayon.js
  src/services/inbox/getInbox.js
  src/services/inbox/inboxQueries.js
  src/services/inbox/inboxTransform.js
  src/services/inbox/updateInbox.js
  src/services/userDashboard/userDashboardHelpers.js
Labels: epic

#481 Web Preview: Versions selector
  src/components/Feed/ActivityVersions/ActivityVersions.jsx
  src/components/ShortcutWidget/ShortcutWidget.jsx
  src/components/VersionSelectorTool/PreviewVersionDropdown/PreviewVersionDropdown.jsx
  src/components/VersionSelectorTool/PreviewVersionDropdown/PreviewVersionDropdown.styled.js
  src/components/VersionSelectorTool/VersionSelectorTool.jsx
  src/components/VersionSelectorTool/VersionSelectorTool.styled.js
  src/components/VersionSelectorTool/hooks/usePreviewShortcuts.jsx
  src/containers/Preview/Preview.jsx
  src/containers/Preview/Preview.styled.js
  src/containers/Preview/PreviewDialog.jsx
  src/features/preview.js
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/services/preview/getPreview.js
  src/services/preview/perviewQueries.js
Labels: feature

#484 Web Preview: Version details panel and feed
  src/components/VersionSelectorTool/VersionSelectorTool.jsx
  src/containers/Preview/Preview.jsx
  src/containers/Preview/Preview.styled.js
  src/containers/Preview/PreviewDetailsPanel.jsx
  src/containers/Preview/PreviewDialog.jsx
  src/containers/Preview/PreviewPlayer.jsx
  src/context/shortcutsContext.jsx
  src/features/details.js
Labels: enhancement

#485 fix(bundles): Order dep packages dropdown alphabetically
  src/pages/SettingsPage/Bundles/BundleDepsPicker.jsx
Labels: bug

#491 Details: multi selection could cause overflows
  src/components/Feed/ActivityItem.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
Labels: bug

#492 fix(browser): Show error message on products error
  src/pages/BrowserPage/Products/NoProducts.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/services/product/getProduct.js
Labels: bug
