Repository ynput/ayon-frontend, pull requests merged in 2024-07, with the labels that each got.

#445 Market: Select addon version to download
  src/components/MarketAddonCard/MarketAddonCard.jsx
  src/pages/MarketPage/AddonDetails/AddonDetails.jsx
  src/pages/MarketPage/AddonDetails/AddonDetails.styled.js
  src/pages/MarketPage/AddonDetails/useDownload.js
  src/pages/MarketPage/AddonFilters.jsx
  src/pages/MarketPage/MarketAddonsList.jsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/MarketPage/mergeAddonsData.js
  src/services/addons/updateAddons.js
  src/services/market/getMarket.ts
Labels: feature

#580 Projects: show and manage pinned projects in main projects list
  src/components/CollapseButton.jsx
  src/containers/ProjectMenu/projectMenu.jsx
  src/containers/projectList.jsx
  src/styles/index.scss
Labels: type: enhancement

#564 Applied the validations on login username and password
  src/pages/LoginPage/LoginPage.jsx
Labels: type: bug

#579 Feed: Show new comments in real time
  src/app.jsx
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/containers/Feed/hooks/useCommentMutations.js
  src/containers/Feed/hooks/useTransformActivities.js
  src/containers/WatchActivities.tsx
  src/services/activities/activitiesHelpers.js
  src/services/activities/activityQueries.js
  src/services/activities/getActivities.js
Labels: type: enhancement

#585 Comment: many bug fixes
  src/components/CommentInput/CommentInput.styled.js
  src/components/CommentInput/InputMarkdownConvert.jsx
  src/components/CommentInput/quillToMarkdown.jsx
  src/components/Feed/ActivityCheckbox/ActivityCheckbox.styled.js
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
  src/components/Feed/ActivityReferenceTooltip/ActivityReferenceTooltip.jsx
Labels: type: bug

#588 Feed: Show checklists count
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/FeedFilters/FeedFilters.jsx
  src/containers/WatchActivities.tsx
  src/services/activities/activitiesHelpers.js
  src/services/activities/activityQueries.js
  src/services/activities/getActivities.js
  src/services/activities/updateActivities.js
Labels: type: enhancement

#616 Viewer: Products select
  src/components/ReviewablesSelector/ReviewablesSelector.tsx
  src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.jsx
  src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.styled.js
  src/components/VersionSelectorTool/VersionSelectorTool.jsx
  src/components/VersionSelectorTool/VersionSelectorTool.styled.js
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/Viewer.tsx
  src/containers/Viewer/ViewerDialog.tsx
  src/features/viewer.js
  src/pages/BrowserPage/Products/Products.jsx
Labels: type: enhancement

#617 AppMenu: removed market entry for managers
  src/components/Menu/Menus/AppMenu.jsx
Labels: type: bug

#621 fix(user settings): Only admins can be developers, managers cannot se…
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
Labels: type: bug

#622 Authorization: Managers cannot access addons and bundle settings
  src/pages/SettingsPage/SettingsPage.jsx
Labels: type: bug

#632 Entity Slideout: Right clicking representation closes the slideout
  src/containers/RepresentationsList/RepresentationsList.jsx
Labels: type: bug

#637 New Project: Clicking X top right forces you to Anatomy page
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
Labels: type: bug

#641 Dropdown: Show warning on invalid items
  package.json
  src/components/VersionSelectorTool/ReviewVersionDropdown/ReviewVersionDropdown.jsx
Labels: type: bug

#642 Fixed missing values from dropdown fields in new project anatomy
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
Labels: type: bug

#649 Web Viewer: Product menu search does not work
  src/components/ReviewVersionDropdown/ReviewVersionDropdown.styled.ts
  src/components/ReviewVersionDropdown/ReviewVersionDropdown.tsx
  src/components/ReviewVersionDropdown/index.ts
  src/components/VersionSelectorTool/VersionSelectorTool.jsx
  src/containers/Viewer/Viewer.tsx
Labels: type: bug

#650 Users: Warn when renaming user
  src/components/InfoMessage/InfoMessage.styled.ts
  src/components/InfoMessage/InfoMessage.tsx
  src/components/InfoMessage/index.ts
  src/pages/SettingsPage/UsersSettings/RenameUserDialog.tsx
Labels: type: bug

#631 User: page crashes when attempting to create new users
  src/containers/AccessGroupsDropdown.jsx
  src/containers/AccessGroupsDropdown.tsx
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
Labels: type: bug

#648 Web viewer snap playhead indicator to frame position
  src/containers/VideoPlayer/Trackbar.jsx
  src/containers/VideoPlayer/VideoPlayer.jsx
  src/containers/VideoPlayer/VideoPlayerControls.jsx
Labels: type: bug

#656 Editor: Naming consistency
  src/helpers/checkName.js
Labels: type: bug

#636 Users: Custom form for a adding service user
  src/components/ApiKeyManager.jsx
  src/containers/Feed/hooks/useUserMutations.js
  src/helpers/callbackOnKeyDown.js
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/SettingsPage/UsersSettings/UserAttribForm.jsx
  src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
  src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
Labels: type: enhancement

#658 Reviewables: Reorder and rename reviewables
  src/api/rest.ts
  src/components/ReviewableCard/ReviewableCard.styled.ts
  src/components/ReviewableCard/ReviewableCard.tsx
  src/containers/Actions/Actions.jsx
  src/containers/ReviewablesList/EditReviewableDialog.tsx
  src/containers/ReviewablesList/ReviewablesList.styled.ts
  src/containers/ReviewablesList/ReviewablesList.tsx
  src/containers/ReviewablesList/SortableReviewableCard.tsx
  src/services/review/getReview.ts
  src/services/review/updateReview.ts
Labels: type: enhancement

#654 Users: Fixed renaming dialog username
  src/pages/SettingsPage/UsersSettings/UserList.jsx
  src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
Labels: type: bug

#663 Enhancement: Navigate to browser page on Dashboard task card double click
  src/helpers/routes.ts
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/ListGroup/ListGroup.jsx
  src/pages/UserDashboardPage/hooks/useGetTaskContextMenu.js
Labels: type: enhancement

#671 fix(addons): Sorting addon versions using semver library algorithm
  src/pages/SettingsPage/AddonsManager/AddonsManager.jsx
  src/pages/SettingsPage/AddonsManager/AddonsManagerTable.jsx
  src/pages/SettingsPage/AddonsManager/helpers.js
  src/pages/SettingsPage/AddonsManager/useGetTableData.js
Labels: type: bug

#670 Browser: keyboard changes selection
  src/components/GridLayout.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/Feed/hooks/useTableKeyboardNavigation.ts
  src/containers/Feed/hooks/useTransformActivities.js
  src/containers/hierarchy.jsx
  src/containers/taskList.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/BrowserPage/Products/ProductsGrid.jsx
  src/pages/BrowserPage/Products/ProductsList.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/WorkfilesPage/WorkfileList.jsx
Labels: type: bug

#666 Kanban: Dragging improvements
  src/features/dashboard.js
  src/pages/UserDashboardPage/UserDashboardTasks/ColumnsWrapper.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.styled.js
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumnDropzone.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
Labels: type: bug

#678 589 bundles re check of compatibility on path change
  src/hooks/usePrevious.js
  src/pages/SettingsPage/Bundles/NewBundle.jsx
Labels: type: bug

#677 Comment: Cycling through attachments via keyboard or mouse
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/FileUploadCard/FileUploadCard.jsx
  src/containers/Feed/Feed.jsx
  src/containers/FileUploadPreview/FileUploadPreview.jsx
  src/containers/FileUploadPreview/FileUploadPreview.styled.js
  src/containers/FileUploadPreview/hooks/useAttachmentNavigation.js
  src/containers/FilesGrid/FilesGrid.jsx
  src/features/context.js
Labels: type: enhancement

#684 Settings: numeric inputs for decimal and negative numbers
  src/containers/SettingsEditor/widgets.jsx
Labels: type: bug

#682 Settings: scroll to staged value
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/AddonSettings/SettingsChangesTable.jsx
  src/containers/SettingsEditor/SettingsEditor.jsx
  src/pages/SettingsPage/SettingsAddon.jsx
Labels: type: enhancement

#674 Watchers: Get important notifications about any entity
  package.json
  src/api/rest.ts
  src/components/EntityPath/EntityPath.styled.ts
  src/components/EntityPath/EntityPath.tsx
  src/components/EntityPath/index.ts
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanel.styled.js
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/DetailsPanel/helpers/getEntityPathData.ts
  src/containers/Watchers/Watchers.tsx
  src/containers/Watchers/index.ts
  src/features/dashboard.js
  src/pages/InboxPage/Inbox/Inbox.jsx
  src/pages/InboxPage/InboxDetailsPanel.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCardDraggable.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
  src/services/ayon.ts
  src/services/entity/updateEntity.js
  src/services/userDashboard/userDashboardHelpers.js
  src/services/watchers.ts
  src/styles/index.scss
Labels: type: feature

#688 Inbox and Feed fixes
  src/components/CommentInput/CommentInput.jsx
  src/components/EntityPath/EntityPath.styled.ts
  src/components/EntityPath/EntityPath.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/helpers/getEntityPathData.ts
  src/containers/Feed/Feed.jsx
  src/containers/Feed/hooks/useCommentMutations.js
  src/pages/InboxPage/hooks/useGroupMessages.js
  src/services/userDashboard/userDashboardHelpers.js
Labels: type: bug

#675 Addons: Added senderId to iframe url to always refresh html content
  src/pages/SettingsPage/SettingsAddon.jsx
Labels: type: enhancement

#691 Global: Bugs cleanup
  package.json
  src/components/CommentInput/CommentInput.jsx
  src/components/MeOrUserSwitch/MeOrUserSwitch.jsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/status/statusSelect.jsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanel.styled.js
  src/containers/DetailsPanel/DetailsPanelFiles/DetailsPanelFiles.tsx
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/RepresentationsList/RepresentationsList.jsx
  src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.jsx
  src/pages/ProjectDashboard/panels/ProjectDetails/ProjectDetails.styled.js
  src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx
  src/services/activities/updateActivities.js
Labels: type: bug

#694 Addon: Folder Picker
  src/pages/ProjectAddon.jsx
Labels: type: enhancement
