Repository ynput/ayon-frontend, pull requests merged in 2024-06, with the labels that each got.

#490 Browser: Version select replace prime react with arc dropdown
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/BrowserPage/Products/VersionList.jsx
Labels: maintenance

#488 Activity Feed: Improve mention suggestions
  src/components/CommentMentionSelect/CommentMentionSelect.jsx
  src/components/CommentMentionSelect/CommentMentionSelect.styled.js
  src/components/Feed/ActivityDate.jsx
  src/containers/Feed/mentionHelpers/getMentionOptions.js
  src/containers/Feed/mentionHelpers/getMentionTasks.js
  src/containers/Feed/mentionHelpers/getMentionVersions.js
  src/pages/BrowserPage/BrowserDetailsPanel.jsx
  src/services/activities/activityQueries.js
Labels: enhancement

#497 Dashboard: Tasks should use latest version thumbnail if no task thumbnailId
  src/services/userDashboard/userDashboardHelpers.js
  src/services/userDashboard/userDashboardQueries.js
Labels: bug

#493 Comment: reference link styling, deleting and tooltips
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInput.styled.js
  src/components/CommentInput/hooks/useMentionLink.js
  src/components/CommentInput/modules/index.js
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/activityMarkdownComponents.jsx
  src/components/Feed/ActivityHeader/ActivityHeader.jsx
  src/components/Feed/ActivityReference/ActivityReference.jsx
  src/components/Tooltips/EntityTooltip/EntityTooltip.styled.js
  src/containers/Feed/Feed.jsx
  src/containers/Feed/hooks/useReferenceTooltip.js
  src/features/details.js
Labels: enhancement

#494 Attributes: Min and max values
  src/components/MinMaxField/MinMaxField.jsx
  src/containers/attributes/attributeEditor.jsx
Labels: enhancement

#496 Mentions: Mention a version or task from a link
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/helpers.jsx
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityReferenceTooltip/ActivityReferenceTooltip.jsx
  src/containers/Feed/Feed.jsx
  src/containers/Feed/mentionHelpers/getMentionOptions.js
  src/containers/Feed/mentionHelpers/getMentionTasks.js
  src/containers/Feed/mentionHelpers/getMentionUsers.js
  src/containers/Feed/mentionHelpers/getMentionVersions.js
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/services/activities/activitiesHelpers.js
  src/services/activities/activityQueries.js
  src/services/activities/getActivities.js
  src/services/mentions/getMentions.js
  src/services/mentions/mentionTransformations.js
  src/services/userDashboard/getUserDashboard.js
  src/services/userDashboard/userDashboardQueries.js
Labels: feature

#502 Menu: Studio settings and Project settings go to wrong tabs
  src/components/Menu/Menus/AppMenu.jsx
Labels: bug

#503 Feed: mentioning another entity invalidates its feed
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInput.styled.js
  src/components/CommentInput/hooks/useMentionLink.js
  src/components/CommentInput/quillToMarkdown.jsx
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/containers/Feed/Feed.jsx
  src/containers/Feed/hooks/useCommentMutations.js
  src/containers/Feed/hooks/useTransformActivities.js
  src/services/activities/getActivities.js
Labels: bug

#505 Workfiles: fix double slashes when roots are replaced
  src/pages/WorkfilesPage/WorkfileDetail.jsx
Labels: bug

#509 Tasks: thumbnail does not always use latest version
  src/components/ListItem/ListItem.jsx
  src/containers/Feed/Feed.jsx
  src/services/userDashboard/userDashboardHelpers.js
  src/services/userDashboard/userDashboardQueries.js
Labels: bug

#511 Project anatomy: show error message with the reason when saving fails
  src/pages/ProjectManagerPage/ProjectAnatomy.jsx
Labels: bug

#519 Editor: Assignee column align left
  package.json
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/ListItem.styled.js
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/pages/EditorPage/EditorPanel.jsx
  src/pages/EditorPage/utils.jsx
  src/pages/TeamsPage/CreateNewTeam/CreateNewTeam.jsx
Labels: bug

#520 Editor: onNewChanges patches rather than overwrites changes
  src/features/editor.js
  src/pages/EditorPage/EditorPanel.jsx
Labels: bug

#522 Services: data fetching rewrite
  src/pages/ServicesPage/NewServiceDialog.jsx
  src/pages/ServicesPage/ServicesPage.jsx
  src/services/ayon.js
  src/services/services/getServices.js
  src/services/services/updateServices.js
Labels: maintenance

#527 Bundles: Comparing latest version takes suffixes into consideration
  src/pages/SettingsPage/Bundles/BundlesAddonList.jsx
Labels: bug

#530 Editor: Check if indirect child has any parent with ownAttrib
  src/pages/EditorPage/EditorPage.jsx
  src/pages/EditorPage/NewEntity.jsx
Labels: bug

#533 Dashboard: keep selected projects in sync with open project
  src/containers/ProjectMenu/projectMenu.jsx
  src/features/dashboard.js
Labels: bug

#537 Chore: Fix typos
  src/components/AttribForm/AttribForm.jsx
  src/components/FolderSequence/FolderSequence.jsx
  src/components/SearchDropdown.jsx
  src/components/status/statusField.jsx
  src/containers/AddonList.jsx
  src/containers/SettingsEditor/fields.jsx
  src/context/pasteContext.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/OnBoarding/util/OnBoardingContext.jsx
  src/pages/ProjectPage.jsx
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
  src/pages/SettingsPage/Bundles/NewBundle.jsx
  src/pages/SettingsPage/UsersSettings/UserList.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/pages/TeamsPage/TeamsPage.jsx
Labels: maintenance

#539 Browser: you can now properly filter versions with multiple folders selected.
  src/hooks/useSearchFilter.js
  src/pages/BrowserPage/Products/Products.jsx
Labels: bug

#535 Tasks: Show all tasks and select all users
  package.json
  src/components/MeOrUserSwitch/MeOrUserSwitch.jsx
  src/components/MeOrUserSwitch/MeOrUserSwitch.styled.js
  src/features/dashboard.js
  src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
Labels: feature

#541 feed only merge activities within 1 minute period
  src/containers/Feed/helpers/mergeSimilarActivities.js
Labels: bug

#547 Dashboard: Increase tasks loading speeds by 16x
  gen/graphql.schema.json
  package.json
  src/api/graphql.ts
  src/components/ListItem/ListItem.jsx
  src/components/MeOrUserSwitch/MeOrUserSwitch.jsx
  src/components/MeOrUserSwitch/MeOrUserSwitch.styled.js
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/Feed/hooks/useScrollToHighlighted.js
  src/features/dashboard.js
  src/helpers/convertAccessGroupsData.ts
  src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/ListGroup/ListGroup.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardKanBan.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/transformKanbanTasks.ts
  src/pages/UserDashboardPage/util/getFilteredTasks.js
  src/pages/UserDashboardPage/util/usePrefetchEntity.js
  src/services/ayon.ts
  src/services/entity/getEntityPanel.js
  src/services/entity/updateEntity.js
  src/services/userDashboard/getUserDashboard.js
  src/services/userDashboard/getUserDashboard.ts
  src/services/userDashboard/getUserProjectsAccess.ts
  src/services/userDashboard/gql/GetKanban.graphql
  src/services/userDashboard/gql/GetKanbanProjectUsers.graphql
  src/services/userDashboard/gql/GetKanbanTasks.graphql
  src/services/userDashboard/gql/KanbanFragment.graphql
  src/services/userDashboard/userDashboardQueries.js
Labels: enhancement

#552 Help menu label: `Graphql Explorer` -> `GraphQL Explorer`
  src/components/Menu/Menus/HelpMenu.jsx
Labels: maintenance

#553 Settings: Fix copying empty project-level values
  src/containers/CopySettings/CopySettingsDialog.jsx
  src/containers/CopySettings/CopySettingsNode.jsx
Labels: bug

#558 Feed: patch ALL activity caches
  src/services/activities/updateActivities.js
Labels: bug

#566 Project menu: sync pinned projects across users devices
  src/containers/ProjectMenu/projectMenu.jsx
  src/services/user/updateUser.js
Labels: enhancement

#573 fix(Browser): Selecting a status from versions list breaks selection
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/services/entity/getEntityPanel.js
  src/services/userDashboard/userDashboardQueries.js
Labels: type: bug

#574 Bootstrap: Do not create prod bundle if prod bundle already exists
  package.json
  src/pages/OnBoarding/Step/AddonSelectStep.jsx
  src/pages/OnBoarding/util/OnBoardingContext.jsx
Labels: type: bug

#575 Comment: Exact dates and toolbar position
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/components/Feed/ActivityComment/ActivityComment.styled.js
  src/components/Feed/ActivityDate.jsx
  src/components/Feed/ActivityHeader/ActivityHeader.jsx
  src/components/Feed/ActivityHeader/ActivityHeader.styled.js
Labels: type: enhancement

#576 Bootstrap: Add platform selection step
  src/components/AddonCard/AddonCard.styled.js
  src/pages/AccountPage/DownloadsPage/DownloadsPage.jsx
  src/pages/OnBoarding/OnBoardingPage.jsx
  src/pages/OnBoarding/Step/AddonSelectStep.jsx
  src/pages/OnBoarding/Step/PlatformSelectStep.jsx
  src/pages/OnBoarding/Step/ProgressInstall.jsx
  src/pages/OnBoarding/Step/index.js
  src/pages/OnBoarding/util/OnBoardingContext.jsx
Labels: type: enhancement
