Repository ynput/ayon-frontend, pull requests merged in 2024-08, with the labels that each got.

#689 Activities: collapsing add/remove activities for same user
  src/components/Feed/ActivityAssigneeChange/ActivityAssigneeChange.styled.js
  src/containers/Feed/Feed.jsx
  src/containers/Feed/helpers/groupMinorActivities.js
  src/containers/Feed/hooks/useTransformActivities.js
Labels: type: bug

#699 Tasks List: Do not show empty groups in listview
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
Labels: type: bug

#692 Details panel: Click on path to open slide out
  gen/graphql.schema.json
  src/api/graphql.ts
  src/components/EntityPath/EntityPath.styled.ts
  src/components/EntityPath/EntityPath.tsx
  src/components/EntityPath/SegmentProvider.tsx
  src/components/EntityPath/VersionsPathSelect/VersionsPathSelect.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanel.styled.js
  src/containers/DetailsPanel/helpers/getEntityPathData.ts
  src/containers/DetailsPanel/hooks/useGetEntityPath.ts
  src/containers/hierarchy.jsx
  src/pages/BrowserPage/Products/NoProducts.jsx
  src/pages/EditorPage/EditorPage.jsx
  src/services/entity/getEntity.js
  src/services/entity/gql/GetProductVersions.graphql
  src/services/getHierarchy.js
  src/services/getHierarchy.ts
Labels: type: feature

#696 Launcher authentication
  src/api/rest.ts
  src/app.jsx
  src/pages/LauncherAuthPage/LauncherAuthPage.tsx
  src/pages/LauncherAuthPage/index.ts
  src/pages/LoginPage/LoginPage.jsx
  src/services/auth/getAuth.js
Labels: type: feature

#700 Activities: feed cannot identify status changes for multiple selected folders/tasks/versions
  src/components/Feed/ActivityGroup/ActivityGroup.jsx
  src/components/Feed/ActivityItem.jsx
  src/components/Feed/ActivityStatusChange/ActivityStatusChange.jsx
  src/components/Feed/ActivityStatusChange/hooks/getContextParents.js
  src/containers/Feed/helpers/mergeSimilarActivities.js
  src/containers/Feed/hooks/useTransformActivities.js
Labels: type: enhancement

#702 Attachments: preview bugs
  src/containers/FileUploadPreview/FileUploadPreview.jsx
  src/containers/FileUploadPreview/FileUploadPreview.styled.js
Labels: type: bug

#705 enhancement(users): Greyed out rows - icons included - for inactive u…
  src/pages/SettingsPage/UsersSettings/UserList.jsx
  src/pages/SettingsPage/UsersSettings/users.scss
Labels: type: enhancement

#707 Reviewables: Show play icon when entity has a reviewable
  gen/graphql.schema.json
  package.json
  src/api/graphql.ts
  src/api/rest.ts
  src/components/Feed/ActivityVersions/ActivityVersions.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
  src/pages/BrowserPage/Products/ProductsGrid.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.jsx
  src/services/product/getProduct.js
  src/services/userDashboard/gql/KanbanFragment.graphql
  src/services/userDashboard/userDashboardHelpers.js
  src/services/userDashboard/userDashboardQueries.js
Labels: type: enhancement

#706 Market: Show addon links
  src/helpers/url.ts
  src/pages/MarketPage/AddonDetails/AddonDetails.jsx
  src/pages/MarketPage/AddonDetails/AddonDetails.styled.js
Labels: type: enhancement

#711 Anatomy Presets: Rework primary and default
  src/pages/ProjectManagerPage/NewProjectDialog/AnatomyPresetDropdown.jsx
  src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
  src/pages/SettingsPage/AnatomyPresets/PresetList.jsx
Labels: type: bug

#714 fix(addons) Using a link instead of button for external links section
  src/pages/MarketPage/AddonDetails/AddonDetails.jsx
  src/pages/MarketPage/AddonDetails/AddonDetails.styled.js
Labels: type: bug

#721 Refactor temporal milestone declaration
  src/containers/CopySettings/CopySettingsNode.jsx
Labels: type: maintenance

#444 Testing: setup playwright and first basic end to end tests
  .gitignore
  package.json
  playwright.config.js
  src/containers/header/AppHeader.jsx
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
  tests/auth.setup.js
  tests/authentication.spec.ts
  tests/bundles.spec.ts
  tests/fixtures/authenticationPage.ts
  tests/fixtures/bundlePage.ts
  tests/fixtures/folderPage.ts
  tests/fixtures/projectPage.ts
  tests/fixtures/taskPage.ts
  tests/fixtures/userPage.ts
  tests/folders.spec.ts
  tests/projects.spec.ts
  tests/tasks.spec.ts
  tests/users.spec.ts
  vite.config.ts
Labels: type: maintenance

#724 EntityCard: Redesign and style fixes
  package.json
  src/components/GlobalContextMenu.jsx
  src/components/SearchDropdown.jsx
  src/components/Tooltips/EntityTooltip/EntityTooltip.jsx
  src/components/status/statusField.jsx
  src/components/status/statusSelect.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/header/AppNavLinks.jsx
  src/containers/hierarchy.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/BrowserPage/Products/ProductsGrid.jsx
  src/pages/EditorPage/EditorPanel.jsx
  src/pages/EventsPage/EventsPage.jsx
  src/pages/ProjectDashboard/panels/ProjectLatestRow.jsx
  src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
  src/pages/TeamsPage/CreateNewTeam/CreateNewTeam.jsx
  src/pages/TeamsPage/TeamsPage.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.styled.ts
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanCard/KanBanCard.tsx
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/transformKanbanTasks.ts
  src/services/activities/activitiesHelpers.js
  src/styles/index.scss
Labels: type: enhancement

#725 Hierarchy: Fix conflicting selection events
  src/containers/hierarchy.jsx
Labels: type: bug

#731 fix(tasks) Changing status of unselected tasks in list view dashboard…
  src/components/ListItem/ListItem.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/ListGroup/ListGroup.jsx
Labels: type: bug

#727 fix(users) Showing 'none' access users at the bottom of the table whe…
  src/helpers/user.ts
  src/pages/SettingsPage/UsersSettings/UserList.jsx
Labels: type: bug

#737 fix(contextMenu): Fixed manage project url, explicit close context me…
  src/containers/ProjectMenu/projectMenu.jsx
  src/containers/projectList.jsx
Labels: type: bug

#739 fix(taskList): adaptive width after render to avoid width jumping col…
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserDashboardList/UserDashboardList.styled.js
Labels: type: bug

#742 fix(folders): Label takes precendence to name when sorting folders in…
  src/helpers/sortByHelpers.ts
  src/helpers/sortByKey.js
  src/pages/EditorPage/EditorPage.jsx
Labels: type: bug

#745 fix(bundles): Selecting production bundle in bundles settings if none…
  src/pages/SettingsPage/Bundles/Bundles.jsx
Labels: type: bug

#746 fix(tasks): Allowing task filtering by user assignee name/full name also
  src/pages/UserDashboardPage/util/getFilteredTasks.js
Labels: type: enhancement

#744 fix(users): Automatically disabling developer rights when updating us…
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
Labels: type: bug

#749 Bundles: Fixing error on navigating to bundles page when no bundles exist
  src/pages/SettingsPage/Bundles/Bundles.jsx
Labels: type: bug

#756 Bundles: Initial bundle selection is not influenced by bundleList changes
  src/pages/SettingsPage/Bundles/Bundles.jsx
Labels: type: bug

#765 Settings: Color Picker dialog size broken in settings
  package.json
Labels: type: bug

#758 Dashboard: Create project button removed for normal users
  src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.styled.js
  src/pages/UserDashboardPage/UserDashboardNoProjects/UserDashboardNoProjects.tsx
Labels: type: bug
