Repository ynput/ayon-frontend, pull requests merged in 2024-09, with the labels that each got.

#754 URI: Sync URI in the address URL (share context with URL)
  src/constants/index.ts
  src/containers/Breadcrumbs/Breadcrumbs.jsx
  src/containers/Breadcrumbs/Breadcrumbs.styled.js
  src/containers/ProjectMenu/hooks/useProjectSelectDispatcher.ts
  src/containers/ProjectMenu/projectMenu.jsx
  src/containers/header/AppNavLinks.jsx
  src/containers/projectList.jsx
  src/features/context.js
  src/features/middleware/searchParamsMiddleware.js
  src/helpers/url.ts
  src/hooks/useAyonNavigate.js
  src/index.jsx
  src/pages/BrowserPage/Products/Products.jsx
  src/pages/ProjectPage.jsx
  src/pages/UserDashboardPage/UserDashboardTasks/UserTasksContainer.jsx
Labels: type: feature

#769 Feed: new comments disappearing
  src/components/CommentInput/CommentInput.jsx
  src/components/Feed/ActivityComment/ActivityComment.jsx
  src/containers/Feed/Feed.jsx
  src/containers/Feed/hooks/useCommentMutations.js
  src/services/activities/updateActivities.js
Labels: type: bug

#772 Context Menu: Manage project actions are not working
  src/containers/ProjectMenu/projectMenu.jsx
  src/containers/projectList.jsx
Labels: type: bug

#752 Settings: Migrate settings by bundle
  gen/openapi-config.ts
  playwright.config.js
  src/api/rest/bundles.ts
  src/app.jsx
  src/containers/AddonSettings/VariantSelector.jsx
  src/containers/BundleDropdown.jsx
  src/containers/BundleDropdown.tsx
  src/pages/SettingsPage/Bundles/BundleForm.jsx
  src/pages/SettingsPage/Bundles/BundleFormLoading.tsx
  src/pages/SettingsPage/Bundles/BundleList.jsx
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/pages/SettingsPage/Bundles/Bundles.styled.js
  src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.styled.ts
  src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.tsx
  src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDropdown.tsx
  src/pages/SettingsPage/Bundles/NewBundle.jsx
  src/services/bundles/updateBundles.ts
  tests/bundles.spec.ts
  tests/fixtures/bundlePage.ts
  tsconfig.json
Labels: type: feature

#775 Thumbnail: Right click to upload
  src/components/EntityThumbnailUploader/EntityThumbnailUploader.styled.tsx
  src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx
  src/components/EntityThumbnailUploader/ThumbnailUploaderProvider.tsx
  src/components/ThumbnailUploader/ThumbnailUploader.styled.ts
  src/components/ThumbnailUploader/ThumbnailUploader.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.jsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
  src/hooks/useFocused.js
  src/pages/BrowserPage/BrowserDetailsPanel.jsx
  src/pages/EditorPage/EditorPanel.jsx
  src/pages/EditorPage/EditorPanel.styled.js
  src/pages/EditorPage/StackedThumbnails.jsx
  src/services/userDashboard/userDashboardHelpers.js
Labels: type: bug

#779 Inbox: Toast notification when users add themselves as watchers
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/Watchers/Watchers.tsx
  src/pages/InboxPage/InboxDetailsPanel.jsx
Labels: type: feature

#781 Breadcrumbs: Breadcrumb component adapts to available space to avoid overlapping
  src/containers/Breadcrumbs/Breadcrumbs.styled.js
  src/containers/header/AppHeader.jsx
Labels: type: bug

#783 Entity Path: Populating correct version id in breadcrumb segments data
  src/containers/DetailsPanel/helpers/getEntityPathData.ts
Labels: type: bug

#789 Update product type `vdb` to `vdbcache` name for icon
  src/features/project.js
Labels: type: bug

#793 Editor: Scrolling not working & details/form gap missing in details panel
  src/components/EntityThumbnailUploader/EntityThumbnailUploader.styled.tsx
  src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx
  src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.js
Labels: type: bug

#790 Bundles: Avoiding form reset on bundle addon version changes
  src/pages/SettingsPage/Bundles/NewBundle.jsx
Labels: type: bug

#800 URI: Removed extra url encoding when synching URI with url param
  src/features/middleware/searchParamsMiddleware.js
Labels: type: bug

#801 Global: 401 error not handled correctly
  src/services/ayon.ts
Labels: type: bug

#804 Tasks Progress: Tasks inside root folders
  src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
  src/containers/TasksProgress/helpers/formatTaskProgressForTable.ts
  src/containers/TasksProgress/helpers/useFolderSort.ts
Labels: type: bug

#788 708 editor enum dropdown fixes and enhancements remade
  package.json
  src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx
  src/pages/EditorPage/EditorPage.jsx
  src/pages/EditorPage/EditorPanel.jsx
  src/pages/EditorPage/EditorPanel/EditorPanel.jsx
  src/pages/EditorPage/EditorPanel/EditorPanel.styled.js
  src/pages/EditorPage/EditorPanel/EntityTumbnailUploaderRow.tsx
  src/pages/EditorPage/EditorPanel/EnumRow.tsx
  src/pages/EditorPage/EditorPanel/TagFormRow.tsx
  src/pages/EditorPage/EditorPanel/helper/callbacks.js
  src/pages/EditorPage/EditorPanel/helper/entityHelpers.ts
  src/pages/EditorPage/fields/ToolsField.jsx
  src/pages/EditorPage/utils.jsx
Labels: type: enhancement

#805 603 feed emoji reaction
  .vscode/launch.json
  src/api/rest/activities.ts
  src/components/Feed/ActivityComment/ActivityComment.tsx
  src/components/Feed/ActivityComment/mappers.ts
  src/components/ReactionContainer/ExistingReactions.tsx
  src/components/ReactionContainer/Reaction.tsx
  src/components/ReactionContainer/ReactionPanelOpener.tsx
  src/components/ReactionContainer/Reactions.styled.ts
  src/components/ReactionContainer/Reactions.tsx
  src/components/ReactionContainer/helpers.ts
  src/components/ReactionContainer/types.ts
  src/features/context.js
  src/services/activities/activityQueries.js
  src/services/reaction/updateReaction.ts
  tests/fixtures/browserPage.ts
  tests/fixtures/bundlePage.ts
  tests/reactions.spec.ts
Labels: type: feature

#807 fix(onboarding): Added Linux EL9 disclaimer on platform selection as …
  src/components/PlatformSelect/PlatformSelect.tsx
Labels: type: bug

#776 Access Groups: Use new rest types
  src/api/rest/accessGroups.ts
  src/services/accessGroups/getAccessGroups.ts
Labels: type: maintenance

#808 Bundles: Cancelling file upload on window close
  src/components/AddonDialog/AddonDialog.jsx
  src/pages/SettingsPage/AddonInstall/AddonInstall.jsx
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
  src/services/queryUpload.js
Labels: type: bug

#816 Viewer: Slide out not showing
  src/containers/DetailsPanel/DetailsPanelSlideOut/DetailsPanelSlideOut.jsx
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/ViewerDialog.tsx
Labels: type: bug

#787 Copy settings: skip overrides that aren't in the same scope
  src/containers/CopySettings/CopySettingsNode.jsx
Labels: type: bug

#812 Viewer: Show dropzone when no reviewables
  src/containers/ReviewablesList/ReviewablesList.styled.ts
  src/containers/ReviewablesList/ReviewablesList.tsx
  src/containers/ReviewablesList/ReviewablesUpload.styled.tsx
  src/containers/ReviewablesList/ReviewablesUpload.tsx
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/Viewer.tsx
  src/containers/Viewer/ViewerComponent.tsx
  src/containers/Viewer/ViewerDialog.tsx
Labels: type: enhancement

#825 Settings: improve compact layout in settings
  src/containers/SettingsEditor/SettingsEditor.sass
  src/containers/SettingsEditor/fields.jsx
Labels: type: bug

#829 Bundles: Dev path incorrectly updating between bundles
  src/pages/SettingsPage/Bundles/BundlesAddonList.jsx
Labels: type: bug

#830 Cloud: show trial banner
  gen/graphql.schema.json
  gen/openapi-config.ts
  package.json
  src/api/graphql.ts
  src/api/rest/cloud.ts
  src/app.jsx
  src/components/TrialBanner/TrialBanner.styled.ts
  src/components/TrialBanner/TrialBanner.tsx
  src/components/TrialBanner/helpers/getSubscribeLink.ts
  src/components/TrialBanner/helpers/getTrialDates.ts
  src/containers/TrialEnded/TrialEnded.styled.ts
  src/containers/TrialEnded/TrialEnded.tsx
  src/containers/attributes/enumEditor.jsx
  src/features/user.js
  src/hooks/useCustomerly.ts
  src/pages/LoginPage/AuthLink.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styled.jsx
  src/services/cloud/cloud.ts
  src/services/user/getUsers.ts
  src/services/user/gql/GetActiveUsersCount.graphql
  src/services/user/gql/GetAllProjectUsers.graphql
Labels: type: maintenance
