Repository ynput/ayon-frontend, pull requests merged in 2024-11, with the labels that each got.

#909 Settings: Basic search filtering
  package.json
  src/components/SearchDropdown/SearchDropdown.styled.tsx
  src/components/SearchDropdown/SearchDropdown.tsx
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/AddonSettings/AddonSettingsPanel.jsx
  src/containers/AddonSettings/SettingsListHeader.tsx
  src/containers/AddonSettings/searchTools.ts
  src/containers/SettingsEditor/FormTemplates/ArrayFieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/FieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/searchMatcher.ts
  src/containers/SettingsEditor/SettingsEditor.jsx
  src/containers/SettingsEditor/SettingsEditor.sass
  src/pages/EditorPage/EditorPage.jsx
Labels: type: enhancement

#924 Editor: Displaying correctly numeric 0/empty values
  src/containers/SettingsEditor/SettingsEditor.jsx
  src/pages/EditorPage/EditorPanel/EditorPanel.jsx
  src/pages/EditorPage/EditorPanel/helper/entityHelpers.ts
Labels: type: bug

#937 Settings: Remove projects panel & project level access groups from user settings page
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessGroupsForm/UserAccessGroups/UserAccessGroups.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessGroupsForm/UserAccessGroups/UserAccessGroups.styled.js
  src/pages/SettingsPage/UsersSettings/UserAccessGroupsForm/UserAccessGroupsForm.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessGroupsForm/UserAccessGroupsProjects/UserAccessGroupsProjects.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessGroupsForm/UserAccessGroupsProjects/UserAccessGroupsProjects.styled.js
  src/pages/SettingsPage/UsersSettings/UsersSettings.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
Labels: type: maintenance

#877 Permissions: More granular access and Project Access page
  gen/openapi-config.ts
  src/api/rest/access.ts
  src/api/rest/permissions.ts
  src/api/rest/project.ts
  src/containers/AddonSettings/AddonSettings.jsx
  src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
  src/containers/SettingsEditor/SettingsEditor.sass
  src/containers/SettingsEditor/Widgets/TextWidget.tsx
  src/containers/projectList.jsx
  src/context/shortcutsContext.jsx
  src/features/user.js
  src/helpers/platform.ts
  src/helpers/string.ts
  src/hooks/useUserProjectPermissions.ts
  src/pages/ProjectManagerPage/ProjectAnatomy.jsx
  src/pages/ProjectManagerPage/ProjectManagerPage.jsx
  src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
  src/pages/ProjectManagerPage/ProjectManagerPageLayout.jsx
  src/pages/ProjectManagerPage/Users/AccessGroupsCell.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccess.styled.ts
  src/pages/ProjectManagerPage/Users/ProjectUserAccess.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAccessGroupPanel.styled.ts
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAccessGroupPanel.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAssignDialog.styled.js
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAssignDialog.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessProjectList.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessSearchFilterWrapper.tsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessUserList.tsx
  src/pages/ProjectManagerPage/Users/SplitterThreePanes.tsx
  src/pages/ProjectManagerPage/Users/SplitterTwoPanes.tsx
  src/pages/ProjectManagerPage/Users/UserCell.tsx
  src/pages/ProjectManagerPage/Users/hooks.ts
  src/pages/ProjectManagerPage/Users/mappers.ts
  src/pages/ProjectManagerPage/Users/types.ts
  src/pages/SettingsPage/AccessGroups/AccessGroupDetail.jsx
  src/pages/SettingsPage/AccessGroups/index.jsx
  src/pages/SettingsPage/Bundles/InstallerSelector.jsx
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
  src/pages/WorkfilesPage/WorkfileDetail.jsx
  src/services/permissions/getPermissions.ts
  src/services/project/getProject.ts
  src/services/project/updateProject.js
  src/styles/index.scss
  tests/bundles.spec.ts
  tests/fixtures/browserPage.ts
  tests/fixtures/bundlePage.ts
  tests/fixtures/permissionsPage.ts
  tests/fixtures/projectUserAccessGroupsPage.ts
  tests/fixtures/userPage.ts
  tests/projectUserAccessGroups.spec.ts
  tests/reactions.spec.ts
Labels: type: feature, sponsored
