Repository ynput/ayon-frontend, pull requests merged in 2025-09, with the labels that each got.

#1328 Expose ports for new service
  src/pages/ServicesPage/NewServiceDialog.jsx
Labels: type: enhancement

#1438 Home: Task Open in browser fix
  src/pages/UserDashboardPage/UserDashboardTasks/KanBanColumn/KanBanColumn.jsx
Labels: type: bug

#1444 User access page error
  src/pages/ProjectManagerPage/Users/mappers.ts
Labels: type: bug

#1404 Add custom protocol fail message
  shared/src/hooks/useActionTriggers.ts
  shared/src/hooks/useCustomProtocolCheck.ts
Labels: type: bug

#1492 Move RenameForm to shared folder
  shared/src/components/RenameForm/RenameForm.tsx
  shared/src/components/RenameForm/index.ts
  shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
  shared/src/containers/ProjectTreeTable/widgets/NameWidget.tsx
  shared/src/util/checkName.ts
  shared/src/util/index.ts
  src/components/NewEntity/NewEntity.tsx
  src/context/NewEntityContext.tsx
  src/pages/TeamsPage/CreateNewTeam/CreateNewTeam.jsx
Labels: type: maintenance

#1494 Overview: Creating new entity should set label with autogen name #1356
  src/components/NewEntity/NewEntity.tsx
  src/components/NewEntity/NewEntityForm.tsx
  src/context/NewEntityContext.tsx
Labels: type: enhancement

#1498 Revert "Merge pull request #1404 from ynput/820-custom-protocol-message"
  shared/src/hooks/useActionTriggers.ts
  shared/src/hooks/useCustomProtocolCheck.ts
Labels: type: maintenance

#1496 Feed: New version activity date overflow #1470
  shared/src/containers/Feed/components/ActivityDate.tsx
  shared/src/containers/Feed/components/ActivityVersions/ActivityVersions.styled.ts
  shared/src/containers/Feed/components/ActivityVersions/ActivityVersions.tsx
Labels: type: bug

#1500 Rename: hasVersions prevents name change and disabled reason why
  shared/src/components/RenameForm/RenameForm.tsx
  shared/src/containers/ProjectTreeTable/buildTreeTableColumns.tsx
  shared/src/containers/ProjectTreeTable/context/ProjectDataContext.tsx
  shared/src/containers/ProjectTreeTable/hooks/useBuildProjectDataTable.ts
  shared/src/containers/ProjectTreeTable/hooks/useCellContextMenu.ts
  shared/src/containers/ProjectTreeTable/hooks/useKeyboardNavigation.ts
  shared/src/containers/ProjectTreeTable/types/table.ts
  shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
  shared/src/containers/ProjectTreeTable/widgets/NameWidget.tsx
Labels: type: maintenance

#1499 Overview: When a enum does not exist we should still show it in dropdown to give option unselect.
  shared/src/containers/ProjectTreeTable/widgets/EnumWidget.tsx
Labels: type: bug

#1416 Entity panel: Description formatting support and improved attributes
  package.json
  shared/src/components/DetailsPanelAttributes/DetailsPanelAttributes.tsx
  shared/src/components/DetailsPanelAttributes/DetailsPanelAttributesEditor.tsx
  shared/src/components/DetailsPanelAttributes/components/RenderFieldWidget.tsx
  shared/src/components/DetailsPanelAttributes/index.ts
  shared/src/components/DetailsPanelDetails/BorderedSection.tsx
  shared/src/components/DetailsPanelDetails/DescriptionSection.styles.ts
  shared/src/components/DetailsPanelDetails/DescriptionSection.tsx
  shared/src/components/DetailsPanelDetails/DetailsPanelDetails.tsx
  shared/src/components/DetailsPanelDetails/DetailsSection.tsx
  shared/src/components/DetailsPanelDetails/FieldLabel.tsx
  shared/src/components/DetailsPanelDetails/hooks/index.ts
  shared/src/components/DetailsPanelDetails/hooks/useDescriptionEditor.ts
  shared/src/components/DetailsPanelDetails/hooks/useEntityData.ts
  shared/src/components/DetailsPanelDetails/hooks/useEntityEditing.ts
  shared/src/components/DetailsPanelDetails/hooks/useEntityFields.ts
  shared/src/components/DetailsPanelDetails/hooks/useEntityFormData.ts
  shared/src/components/DetailsPanelDetails/hooks/useMentionSystem.ts
  shared/src/components/DetailsPanelDetails/hooks/useQuillFormats.ts
  shared/src/components/DetailsPanelDetails/index.ts
  shared/src/components/DetailsPanelDetails/types.ts
  shared/src/components/QuillListStyles/QuillListStyles.ts
  shared/src/components/QuillListStyles/index.ts
  shared/src/components/StyledLink/StyledLink.tsx
  shared/src/components/StyledLink/index.ts
  shared/src/components/index.ts
  shared/src/containers/DetailsPanel/DetailsPanel.tsx
  shared/src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.styled.ts
  shared/src/containers/DetailsPanel/DetailsPanelHeader/DetailsPanelHeader.tsx
  shared/src/containers/DetailsPanel/FeedContextWrapper.tsx
  shared/src/containers/DetailsPanel/FeedFilters/FeedFilters.tsx
  shared/src/containers/Feed/components/CommentInput/CommentInput.styled.ts
  shared/src/containers/Feed/components/CommentInput/CommentInput.tsx
  shared/src/containers/Feed/components/CommentInput/modules/index.ts
  shared/src/containers/Feed/components/CommentInput/quillToMarkdown.tsx
  shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
  shared/src/containers/ProjectTreeTable/widgets/TextWidget.tsx
  shared/src/containers/ProjectTreeTable/widgets/TextWidgetInput.tsx
  shared/src/context/DetailsPanelContext.tsx
  shared/src/hooks/index.ts
  shared/src/hooks/useActionTriggers.ts
  shared/src/hooks/useTagStyling.ts
  shared/src/util/clipboardUtils.ts
  shared/src/util/copyToClipboard.ts
  shared/src/util/humanizeFieldName.ts
  shared/src/util/index.ts
  shared/src/util/parseHtmlToPlainTextWithLinks.ts
  src/containers/WatchActivities.tsx
  src/pages/ProjectListsPage/hooks/useNewList.ts
  src/styles/index.scss
  yarn.lock
Labels: type: feature

#1471 Unify guests and external users
  src/components/GuestUserPageLocked.tsx
  src/components/Menu/Menus/UserMenu/UserMenu.jsx
  src/containers/header/AppHeader.jsx
  src/features/user.js
  src/pages/ProjectPage/ProjectPage.tsx
  src/pages/SettingsPage/UsersSettings/UserAccessForm.jsx
  src/pages/SettingsPage/UsersSettings/UserList.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/pages/SettingsPage/UsersSettings/useUserMutations.js
  src/pages/SettingsPage/UsersSettings/userDetail.jsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
Labels: type: maintenance

#1515 Details Panel: Fix displaying description in slider and saving description as markdown
  shared/src/components/DetailsPanelAttributes/DetailsPanelAttributesEditor.tsx
  shared/src/components/DetailsPanelAttributes/components/RenderFieldWidget.tsx
  shared/src/components/DetailsPanelDetails/DescriptionSection.styles.ts
  shared/src/components/DetailsPanelDetails/DescriptionSection.tsx
  shared/src/components/DetailsPanelDetails/hooks/useDescriptionEditor.ts
  shared/src/containers/ProjectTreeTable/widgets/TextWidgetInput.tsx
Labels: type: bug

#1516 Overview: closing multilink dialog with button
  shared/src/components/LinksManager/LinkManagerItem.tsx
  shared/src/components/LinksManager/LinksManager.styled.ts
  shared/src/components/LinksManager/LinksManager.tsx
Labels: type: enhancement

#1524 Cleanup shortcut labels
  shared/src/containers/ProjectTreeTable/hooks/useCellContextMenu.ts
  src/components/ErrorFallback.jsx
  src/components/NewEntity/NewEntity.tsx
  src/containers/VideoPlayer/VideoPlayerControls.jsx
  src/pages/InboxPage/Inbox/Inbox.jsx
  src/pages/ProjectManagerPage/Users/ProjectUserAccessAssignDialog.tsx
  src/pages/SettingsPage/Bundles/BundleDetail.jsx
  src/pages/SettingsPage/Bundles/BundleList.jsx
  src/pages/SettingsPage/Bundles/NewBundle.jsx
  src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
  src/pages/SettingsPage/UsersSettings/newUser.jsx
  src/pages/UserDashboardPage/hooks/useGetTaskContextMenu.js
Labels: type: maintenance

#1537 Task Progress: Expanded selected folders glitch
  src/containers/TasksProgress/components/FolderBody/FolderBody.styled.ts
  src/containers/TasksProgress/components/FolderBody/FolderBody.tsx
Labels: type: bug
