Repository ynput/ayon-frontend, pull requests merged in 2025-02, with the labels that each got.

#1002 License change from Apache 2.0 to FSL-1.1-ALv2
  LICENSE
Labels: type: maintenance, bump minor

#1008 Inbox: Clear all, clears all messages (not just ones on screen)
  src/api/rest/inbox.ts
  src/pages/InboxPage/Inbox/Inbox.jsx
  src/pages/InboxPage/hooks/useUpdateInboxMessage.ts
  src/services/inbox/updateInbox.ts
  src/services/project/ProjectTypes.ts
  src/services/project/getProject.ts
Labels: type: bug, sponsored

#1009 Fix: Slide bug fixes
  src/components/EntityPath/EntityPath.tsx
  src/components/EntityPath/SegmentProvider.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanel.styled.js
  src/containers/Viewer/Viewer.styled.ts
  src/context/uriContext.jsx
Labels: type: bug, sponsored

#919 Server config page
  gen/openapi-config.ts
  src/api/rest/config.ts
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styled.jsx
  src/pages/LoginPage/markdown.js
  src/pages/SettingsPage/ServerConfig/ServerConfig.tsx
  src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx
  src/pages/SettingsPage/SettingsPage.jsx
  src/services/ayon.ts
  src/services/config/getConfig.ts
  src/services/config/updateConfig.ts
Labels: type: feature

#1013 Feed: Editing 1 comment and adding drawings to comments
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/hooks/useAnnotationsSync.ts
  src/components/Feed/ActivityComment/ActivityComment.tsx
  src/containers/DetailsPanel/DetailsPanel.jsx
  src/containers/DetailsPanel/DetailsPanelFloating/DetailsPanelFloating.tsx
  src/containers/Feed/Feed.jsx
  src/context/FeedContext.tsx
  src/features/viewer.ts
Labels: type: bug

#1015 Market: Use V2
  gen/openapi-config.ts
  src/api/rest/market.ts
  src/api/rest/releases.ts
  src/components/AddonsSelectGrid/AddonsSelectGrid.tsx
  src/components/MarketAddonCard/MarketAddonCard.tsx
  src/components/Powerpack/PowerpackButton.tsx
  src/components/Powerpack/PowerpackDialog.tsx
  src/components/PricingLink.tsx
  src/components/Release/ReleasePreset.jsx
  src/components/Release/ReleasePreset.styled.js
  src/components/SubChip/SubChip.tsx
  src/constants/index.ts
  src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerAddons.tsx
  src/containers/ReleaseInstallerDialog/forms/ReleaseInstallerOverview.tsx
  src/containers/ReleaseInstallerDialog/hooks/useReleaseInfo.ts
  src/containers/Slicer/SlicerDropdown.tsx
  src/pages/MarketPage/MarketAddonsList.tsx
  src/pages/MarketPage/MarketDetails/AddonDetails.tsx
  src/pages/MarketPage/MarketDetails/ReleaseDetails.tsx
  src/pages/MarketPage/MarketFilters.tsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/OnBoarding/Step/AddonSelectStep.tsx
  src/styles/index.scss
Labels: type: enhancement

#1017 Disable `1px solid yellow` outline for text widgets
  src/containers/SettingsEditor/Widgets/TextWidget.tsx
Labels: type: bug

#1016 Settings: Delete launcher and dependency files
  gen/openapi-config.ts
  package.json
  src/api/rest/dependencyPackages.ts
  src/api/rest/installers.ts
  src/components/AddonDialog/AddonDialog.jsx
  src/components/FileUploadCard/FileUploadCard.jsx
  src/pages/SettingsPage/AddonInstall/AddonManager.tsx
  src/pages/SettingsPage/AddonInstall/AddonUpload.jsx
  src/pages/SettingsPage/AddonInstall/FilesTable/FilesTable.tsx
  src/pages/SettingsPage/AddonInstall/hooks/useFetchManagerData.ts
  src/pages/SettingsPage/AddonInstall/hooks/useFileManagerMutations.ts
  src/pages/SettingsPage/AddonsManager/BundleStatus/BundleStatus.jsx
  src/pages/SettingsPage/AddonsManager/BundleStatus/BundleStatus.tsx
  src/pages/SettingsPage/Bundles/Bundles.jsx
  src/services/dependencyPackages/updateDependencyPackages.ts
  src/services/installers/getInstallers.ts
  src/services/installers/updateInstallers.ts
Labels: type: enhancement

#1019 Use `delete selected` as string when deleting multiple users instead of all usernames joined together
  src/pages/SettingsPage/UsersSettings/DeleteUserDialog.tsx
Labels: type: enhancement

#1020 Fix typo: `AllProjectsPremissions` -> `AllProjectsPermissions`
  src/hooks/useUserProjectPermissions.ts
Labels: type: enhancement

#1028 Internal: Odd shortcut behaviors
  src/context/shortcutsContext.jsx
Labels: type: bug

#1032 Annotations: pass dimensions correctly for the upcoming new Power Pack version
  src/containers/VideoPlayer/VideoPlayer.jsx
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/ViewerImage.tsx
  src/containers/Viewer/hooks/useViewerAnnotations.ts
Labels: type: enhancement

#1034 Market: Show all addons by default
  src/pages/MarketPage/MarketFilters.tsx
  src/pages/MarketPage/MarketPage.jsx
Labels: type: bug

#1031 Dashboard: Force assignees filter to "me" when user has no permissions to list users
  src/pages/UserDashboardPage/UserDashboardTasks/DashboardTasksToolbar/DashboardTasksToolbar.jsx
  src/services/auth/getAuth.js
Labels: type: bug

#1045 Viewer: display images with portrait aspect ratios correctly
  src/containers/Viewer/Viewer.styled.ts
  src/containers/Viewer/ViewerImage.tsx
  src/containers/Viewer/index.ts
Labels: type: enhancement

#1041 Users: Show total license used
  src/components/LicensesDialog/LicensesDialog.tsx
  src/pages/SettingsPage/UsersSettings/UsersOverview.tsx
Labels: type: enhancement

#1047 Re-enable video autoplay when opening the Viewer using the spacebar
  src/containers/Viewer/Viewer.tsx
Labels: type: bug

#1039 Global Customizations: Allow to remove an uploaded image
  src/pages/SettingsPage/ServerConfig/ServerConfig.tsx
  src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx
Labels: type: enhancement

#1046 Only clear comment field if the submission resulted in a result entry
  src/containers/Feed/Feed.jsx
  src/containers/Feed/hooks/useCommentMutations.js
  src/services/activities/updateActivities.js
Labels: type: enhancement

#1051 Modules: Set min required version for remote load
  src/context/viewerContext.tsx
  src/remote/useLoadModule.ts
Labels: type: bug
