Repository ynput/ayon-frontend, pull requests merged in 2025-05, with the labels that each got.

#1144 Sync with new action response model
  src/containers/Actions/ActionConfigDialog.tsx
  src/containers/Actions/Actions.jsx
  src/containers/Actions/InteractiveActionDialog.tsx
  src/containers/SimpleFormDialog/SimpleFormDialog.tsx
  src/hooks/useActionTriggers.ts
Labels: type: maintenance

#1147 Fix: Copy settings from dev bundle
  src/pages/SettingsPage/Bundles/CopyBundleSettingsDialog/CopyBundleSettingsDialog.tsx
Labels: type: bug

#1150 Remote: Provide remote apps with location
  package.json
  src/remote/Loaders/AppRemoteLoader.tsx
  yarn.lock
Labels: type: maintenance

#1153 Expose an `onUpdateEntity` callback from `DetailsPanelProvider`
  shared/package.json
  shared/src/context/DetailsPanelContext.tsx
  shared/src/hooks/useEntityUpdate.ts
Labels: type: enhancement

#1156 Missing representation list
  shared/src/containers/RepresentationsList/RepresentationsList.tsx
Labels: type: bug

#1155 Allow null status scope
  shared/src/hooks/useScopedStatuses.ts
Labels: type: bug

#1160 Truncate last path segment in DetailsPanel to avoid panel width being affected
  shared/src/components/EntityPath/EntityPath.styled.ts
  shared/src/components/EntityPath/EntityPath.tsx
Labels: type: enhancement

#1161 Settings: Anatomy does not update URI as it is not supported
  src/containers/AnatomyEditor.jsx
  src/containers/Breadcrumbs/Breadcrumbs.jsx
  src/pages/SettingsPage/AnatomyPresets/AnatomyPresets.jsx
  src/services/anatomy/getAnatomy.js
Labels: type: maintenance

#1162 Webactions: Use groupLabel if available
  shared/src/containers/Actions/Actions.tsx
Labels: type: enhancement

#1164 Fix: overview cannot copy empty array and clear field option
  shared/src/containers/ProjectTreeTable/context/ClipboardContext.tsx
  shared/src/containers/ProjectTreeTable/context/clipboard/clipboardUtils.ts
  shared/src/containers/ProjectTreeTable/widgets/CellWidget.tsx
  shared/src/containers/ProjectTreeTable/widgets/DateWidget.tsx
Labels: type: bug

#1175 Fix fetching tooltip data for mentions
  shared/src/containers/Feed/context/FeedContext.tsx
Labels: type: bug

#1180 Details Panel: Details panel thumbnail uses contain
  shared/src/components/Thumbnail/StackedThumbnails.tsx
  shared/src/components/Thumbnail/Thumbnail.styled.ts
Labels: type: bug

#1181 Hide admin addon frontends to non admins (configurable)
  src/pages/ProjectPage/ProjectPage.tsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
Labels: type: enhancement

#1184 Annotations storage improvements
  shared/src/containers/Feed/Feed.tsx
  shared/src/containers/Feed/components/ActivityComment/ActivityComment.tsx
  shared/src/containers/Feed/components/CommentInput/CommentInput.tsx
  shared/src/containers/Feed/components/CommentInput/helpers.tsx
  shared/src/containers/Feed/components/CommentInput/hooks/useAnnotationsSync.ts
  shared/src/containers/Feed/components/CommentInput/hooks/useAnnotationsUpload.ts
  shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.styled.ts
  shared/src/containers/Feed/components/FileUploadCard/FileUploadCard.tsx
  shared/src/containers/Feed/components/FilesGrid/FilesGrid.tsx
  shared/src/containers/Feed/helpers/mergeAnnotationAttachments.ts
  shared/src/containers/Feed/hooks/useCommentMutations.ts
  shared/src/containers/Feed/hooks/useTransformActivities.ts
  shared/src/containers/Feed/index.ts
  shared/src/context/DetailsPanelContext.tsx
  src/pages/ProjectListsPage/context/ListsModulesContext.tsx
Labels: type: enhancement

#1185 Privacy policy note
  src/feedback/FeedbackContext.tsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styled.jsx
Labels: type: maintenance

#1174 Project-level actions
  shared/src/components/SimpleFormDialog/SimpleFormDialog.tsx
  shared/src/containers/Actions/Actions.tsx
  shared/src/hooks/useActionTriggers.ts
  src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx
Labels: type: feature

#1186 Feed: clear feed annotations array if no activities found in feed
  shared/src/containers/Feed/Feed.tsx
Labels: type: bug

#1188 Add activity IDs to feed annotations and highlight activities on annotation click
  shared/src/containers/Feed/Feed.tsx
  shared/src/containers/Feed/components/ActivityComment/ActivityComment.tsx
  shared/src/containers/Feed/index.ts
Labels: type: enhancement

#1190 Settings: Unable to switch from settings to bundles
  src/pages/SettingsPage/Bundles/Bundles.jsx
Labels: type: bug

#1208 URI: Navigation not correctly going to focused entity in browser page
  src/context/UriContext.jsx
Labels: type: bug

#1210 Overview: Fix an issue where the slicer would not show updates to folder changes
  shared/src/containers/ProjectTreeTable/utils/validateUpdateEntities.ts
  src/containers/Slicer/hooks/useHierarchyTable.ts
  src/containers/Slicer/hooks/useTableDataBySlice.ts
  src/context/UriContext.jsx
Labels: type: bug
