Repository ynput/ayon-frontend, pull requests merged in 2025-07, with the labels that each got.

#1289 Overview: Enum dropdown shows hover only for expand
  shared/src/containers/ProjectTreeTable/widgets/EnumCellValue.tsx
  shared/src/containers/ProjectTreeTable/widgets/EnumWidget.tsx
Labels: type: bug

#1283 Review: Create review sessions from version lists
  shared/src/SimpleTable/SimpleTable.styled.ts
  shared/src/api/generated/graphql.ts
  shared/src/api/queries/actions/getActions.ts
  shared/src/api/queries/entityLists/getLists.ts
  shared/src/api/queries/entityLists/gql/GetListsItemsForReviewSession.graphql
  shared/src/api/queries/entityLists/types.ts
  shared/src/api/queries/entityLists/updateLists.ts
  shared/src/containers/Actions/Actions.tsx
  shared/src/containers/Actions/ActionsDropdown/ActionsDropdown.tsx
  src/pages/ProjectListsPage/ProjectListsPage.tsx
  src/pages/ProjectListsPage/components/ListRow/ListRow.styled.ts
  src/pages/ProjectListsPage/components/ListRow/ListRow.tsx
  src/pages/ProjectListsPage/components/NewListDialog/NewListDialogContainer.tsx
  src/pages/ProjectListsPage/components/NewReviewSessionDialog/NewReviewSessionDialog.tsx
  src/pages/ProjectListsPage/components/NewReviewSessionDialog/NewReviewSessionLoading.tsx
  src/pages/ProjectListsPage/context/ListsContext.ts
  src/pages/ProjectListsPage/context/ListsProvider.tsx
  src/pages/ProjectListsPage/hooks/useGetBundleAddonVersion.ts
  src/pages/ProjectListsPage/hooks/useGetListsItemsForReviewSession.ts
  src/pages/ProjectListsPage/hooks/useListContextMenu.ts
  src/pages/ProjectListsPage/hooks/useNewList.ts
  src/pages/ProjectListsPage/util/buildReviewListLabel.ts
  src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx
  src/pages/ReviewPage/OpenReviewSessionButton.tsx
Labels: type: feature

#1301 Project lists redesign
  shared/src/SimpleTable/SimpleTable.styled.ts
  shared/src/SimpleTable/SimpleTable.tsx
  shared/src/SimpleTable/SimpleTableRowTemplate.tsx
  shared/src/SimpleTable/context/SimpleTableContext.tsx
  src/components/Menu/MenuComponents/Menu.styled.js
  src/components/Menu/MenuComponents/MenuContainer.jsx
  src/components/Menu/MenuComponents/MenuItem.jsx
  src/components/Menu/MenuComponents/MenuList.jsx
  src/containers/ProjectsList/ProjectsList.tsx
  src/containers/ProjectsList/ProjectsListRow.tsx
  src/containers/ProjectsList/ProjectsListTableHeader.tsx
  src/containers/ProjectsList/buildProjectsTableData.ts
  src/containers/ProjectsList/hooks/useProjectListUserPreferences.ts
  src/containers/ProjectsList/hooks/useProjectsListContextMenu.ts
  src/containers/ProjectsList/hooks/useProjectsListMenuItems.ts
  src/containers/Slicer/Slicer.tsx
  src/containers/projectList.jsx
  src/pages/ProjectManagerPage/ProjectManagerPageContainer.jsx
  src/pages/ProjectManagerPage/ProjectManagerPageLayout.jsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
Labels: type: enhancement

#1308 Player: Ensure we do not go to frame 0 when switch videos
  src/containers/VideoPlayer/VideoPlayer.jsx
Labels: type: bug

#1322 Opening overview dropdown now updates correct cell
  shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
Labels: type: bug

#1336 Bundles: Dev mode: Include `/client` in placeholder path + add tooltip
  src/pages/SettingsPage/Bundles/BundlesAddonList.jsx
Labels: type: enhancement, community

#1338 Overview: Add selected parent label to new entity dialog
  src/components/NewEntity/NewEntity.tsx
Labels: type: bug
