Repository ynput/ayon-frontend, pull requests merged in 2025-03, with the labels that each got.

#1052 Settings: fix array copy in settings
  src/containers/AddonList.jsx
  src/containers/SettingsEditor/FormTemplates/FieldTemplate.tsx
  src/containers/SettingsEditor/FormTemplates/ObjectFieldTemplate.tsx
  src/helpers/copyToClipboard.js
Labels: type: bug

#1054 Settings: "Global" tab move to left so bundles and studio settings remain close to each other
  src/pages/SettingsPage/SettingsPage.jsx
Labels: type: enhancement, community

#1055 Editor: use errorCode from operation response
  src/pages/EditorPage/EditorPage.jsx
Labels: type: enhancement

#1066 Login: Logo shows without text and full width and height
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styled.jsx
Labels: type: bug

#1065 Show version comment on the version activity in the activity feed
  src/components/Feed/ActivityVersions/ActivityVersions.jsx
  src/components/Feed/ActivityVersions/ActivityVersions.styled.js
  src/containers/Feed/helpers/groupActivityVersions.js
  src/services/activities/activityQueries.js
Labels: type: enhancement, sponsored

#1074 MF: Remove arc module sharing
  src/remote/remoteModulesContext.tsx
  vite.config.ts
Labels: type: maintenance

#1073 Services: Abide by AWS bucket naming rules
  src/pages/ServicesPage/NewServiceDialog.jsx
Labels: type: bug

#1079 Auth: Better handle WS disconnect
  src/context/websocketContext.jsx
Labels: type: bug
