Repository ynput/ayon-frontend, pull requests merged in 2025-08, with the labels that each got.

#1370 Overview: Real time updates
  shared/src/api/generated/graphql.ts
  shared/src/api/queries/folders/getFolders.ts
  shared/src/api/queries/overview/getOverview.ts
  shared/src/api/queries/overview/gql/GetTasksList.graphql
  shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
Labels: type: enhancement

#1368 Page titles should show what page you are on
  index.html
  src/app.tsx
  src/components/DocumentTitle/DocumentTitle.tsx
  src/components/ErrorFallback.jsx
  src/components/Favicon/Favicon.jsx
  src/containers/TrialEnded/TrialEnded.tsx
  src/hooks/useTitle.ts
  src/pages/APIDocsPage.jsx
  src/pages/AccountPage/AccountPage.jsx
  src/pages/EventsPage/EventsPage.jsx
  src/pages/ExplorerPage.jsx
  src/pages/InboxPage/InboxPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/OnBoarding/OnBoardingPage.jsx
  src/pages/PasswordResetPage.jsx
  src/pages/ProjectAddon.jsx
  src/pages/ProjectManagerPage/ProjectManagerPage.jsx
  src/pages/ProjectPage/ProjectPage.tsx
  src/pages/ServicesPage/ServicesPage.jsx
  src/pages/SettingsPage/SettingsPage.jsx
  src/pages/TeamsPage/TeamsPage.jsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
Labels: type: enhancement

#1387 Redirect after login improvements
  src/app.tsx
  src/components/ExternalUserPageLocked.tsx
  src/components/Menu/Menus/UserMenu/UserMenu.jsx
  src/containers/header/AppHeader.jsx
  src/features/user.js
  src/pages/AccountPage/ProfilePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProjectPage/ProjectPage.tsx
  src/pages/UserDashboardPage/UserDashboardPage.jsx
Labels: type: maintenance

#1411 Add tooltip to dependency package file name
  src/pages/SettingsPage/Bundles/BundleDepPackage.jsx
Labels: type: enhancement

#1391 Move folder and task to a different folder
  shared/src/containers/EntityPickerDialog/EntityPickerDialog.tsx
  shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
  shared/src/containers/ProjectTreeTable/hooks/useMoveEntities.ts
  shared/src/containers/ProjectTreeTable/types/overviewContext.ts
  shared/src/containers/SimpleTable/SimpleTable.styled.ts
  shared/src/containers/SimpleTable/SimpleTable.tsx
  shared/src/containers/SimpleTable/SimpleTableRowTemplate.tsx
  src/features/moveEntity.ts
  src/features/store.ts
  src/pages/ProjectOverviewPage/hooks/useOverviewContextMenu.ts
Labels: type: enhancement

#1405 1367 - Fix column header icons
  .gitignore
  shared/src/components/DetailsPanelDetails/DetailsSection.tsx
  shared/src/containers/ProjectTreeTable/ProjectTreeTable.styled.ts
  shared/src/containers/ProjectTreeTable/ProjectTreeTable.tsx
  shared/src/containers/ProjectTreeTable/components/ColumnHeaderMenu.tsx
  shared/src/containers/ProjectTreeTable/components/HeaderActionButton.tsx
  shared/src/containers/ProjectTreeTable/components/index.ts
  shared/src/containers/ProjectTreeTable/index.ts
  shared/src/hooks/useActionTriggers.ts
Labels: type: bug
