Repository ynput/ayon-frontend, pull requests merged in 2025-04, with the labels that each got.

#1086 Changelogs, road maps, help and feedback
  gen/openapi-config.ts
  src/api/rest/auth.ts
  src/api/rest/cloud.ts
  src/app.jsx
  src/components/CompleteProfilePrompt/CompleteProfilePrompt.tsx
  src/components/Menu/MenuComponents/Menu.jsx
  src/components/Menu/MenuComponents/MenuItem.jsx
  src/components/Menu/Menus/AppMenu.jsx
  src/components/Menu/Menus/HelpMenu.jsx
  src/feedback/FeedbackContext.tsx
  src/pages/AccountPage/AccountPage.jsx
  src/services/auth/getAuth.js
  src/services/ayon.ts
  src/services/cloud/cloud.ts
  src/services/user/getUsers.ts
  src/services/user/updateUser.ts
Labels: type: feature

#1087 Projects: Use a regex to generate project code
  gen/openapi-config.ts
  src/api/rest/config.ts
  src/pages/ProjectManagerPage/NewProjectDialog/AnatomyPresetDropdown.jsx
  src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
  src/services/config/getConfig.ts
Labels: type: enhancement

#1090 Settings: Select all option for dropdowns with more than 10 options
  src/containers/SettingsEditor/Widgets/SelectWidget.tsx
Labels: type: bug

#1094 Services: Service details panel and service editing
  gen/openapi-config.ts
  src/api/rest/services.ts
  src/pages/ServicesPage/NewServiceDialog.jsx
  src/pages/ServicesPage/ServiceDetailsPanel.jsx
  src/pages/ServicesPage/ServicesPage.jsx
  src/services/services/getServices.js
  src/services/services/getServices.ts
  src/services/services/updateServices.js
  src/services/services/updateServices.ts
Labels: type: feature

#1096 Actions: Client side triggers
  src/components/ActionsDropdown/ActionsDropdown.jsx
  src/containers/Actions/Actions.jsx
  src/containers/Actions/Actions.styled.js
  src/containers/DetailsPanel/FeedFilters/FeedFilters.styled.js
  src/hooks/useActionTriggers.ts
Labels: type: bug

#1095 Use connected flag of /api/connect response
  src/components/YnputCloud/YnputConnector.jsx
  src/containers/ReleaseInstallerDialog/ReleaseInstallerDialog.tsx
  src/pages/MarketPage/MarketPage.jsx
  src/pages/OnBoarding/Step/BoostrapStart.jsx
  src/pages/OnBoarding/util/OnBoardingContext.jsx
Labels: type: enhancement

#1098 Configurable and interactive actions
  gen/openapi-config.ts
  src/api/rest/actions.ts
  src/components/ActionsDropdown/ActionsDropdown.jsx
  src/containers/Actions/ActionConfigDialog.tsx
  src/containers/Actions/Actions.jsx
  src/containers/Actions/InteractiveActionDialog.tsx
  src/containers/SimpleFormDialog/SimpleFormDialog.tsx
  src/services/actions/actions.ts
  src/services/ayon.ts
Labels: type: feature

#1101 Overview: Sync columns config to user preferences
  shared/src/ProjectTreeTable/context/ColumnSettingsContext.tsx
  src/api/rest/auth.ts
  src/hooks/useColumnsConfig.tsx
  src/pages/ProjectOverviewPage/ProjectOverviewWithProviders.tsx
  src/pages/ProjectOverviewPage/components/ColumnsSettings.tsx
  src/pages/ProjectOverviewPage/context/ProjectDataContext.tsx
  src/pages/ProjectOverviewPage/context/ProjectOverviewContext.tsx
  src/pages/ProjectOverviewPage/hooks/useUserPageConfig.ts
  src/services/auth/getAuth.js
  src/services/user/updateUser.ts
Labels: type: enhancement

#1107 Overview: New entities respect slicer selection
  src/components/NewEntity/NewEntity.tsx
  src/context/NewEntityContext.tsx
  src/pages/ProjectOverviewPage/ProjectOverviewPage.tsx
Labels: type: bug

#1111 Overview: Updating details panel folders will invalidate queries
  src/services/entity/updateEntity.js
  src/services/overview/getOverview.ts
Labels: type: bug

#1112 Overview: Better error messages for clipboard errors
  shared/src/ProjectTreeTable/context/ClipboardContext.tsx
Labels: type: bug

#1114 Overview: Validate field values based on attribute
  shared/src/ProjectTreeTable/context/CellEditingContext.tsx
  shared/src/ProjectTreeTable/widgets/CellWidget.tsx
Labels: type: bug

#1115 useLocalStorage key updates
  shared/src/ProjectTreeTable/context/ProjectTableContext.tsx
  shared/src/hooks/useLocalStorage.ts
  src/containers/TasksProgress/helpers/formatSearchQueryFilters.ts
  src/pages/ProjectOverviewPage/context/ProjectOverviewContext.tsx
Labels: type: bug

#1135 chore: fb tweaks
  src/app.jsx
  src/feedback/FeedbackContext.tsx
Labels: type: maintenance
